mv $HOME/DATA*$DATE*.h5 .
# the following are mounted on brain1 using sshfs
mv $HOME/cam1/FLYDRA_LARGE_MOVIES/*$DATE* .
mv $HOME/cam2/FLYDRA_LARGE_MOVIES/*$DATE* .
mv $HOME/cam3/FLYDRA_LARGE_MOVIES/*$DATE* .
mv $HOME/cam4/FLYDRA_LARGE_MOVIES/*$DATE* .
mv $HOME/cam5/FLYDRA_LARGE_MOVIES/*$DATE* .

mv $HOME/cam1/FLYDRA_SMALL_MOVIES/*$DATE* .
mv $HOME/cam2/FLYDRA_SMALL_MOVIES/*$DATE* .
mv $HOME/cam3/FLYDRA_SMALL_MOVIES/*$DATE* .
mv $HOME/cam4/FLYDRA_SMALL_MOVIES/*$DATE* .
mv $HOME/cam5/FLYDRA_SMALL_MOVIES/*$DATE* .
