# emacs, this is a -*-makefile-*-

include kalman_products.mk

%.kh5 : %.h5
	rm -f $@
	flydra_kalmanize $< -r $(CALFILE) --max-err=$(MAXERR) --min-observations-to-save=$(MINOBS) --dynamic-model=$(MODEL) --force-minimum-eccentricity=$(MIN_ECCENTRICITY) --dest-file $@

%.png : %.kh5 fanout.xml
	rm -f $@
	flydra_analysis_plot_summary -k $< --stim-xml fanout.xml

.PHONY: default figs
