/* Generated by Pyrex 0.9.5.1a on Thu Nov  8 00:36:05 2007 */

#define PY_SSIZE_T_CLEAN
#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#if PY_VERSION_HEX < 0x02050000
  typedef int Py_ssize_t;
  #define PY_SSIZE_T_MAX INT_MAX
  #define PY_SSIZE_T_MIN INT_MIN
  #define PyInt_FromSsize_t(z) PyInt_FromLong(z)
  #define PyInt_AsSsize_t(o)   PyInt_AsLong(o)
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
__PYX_EXTERN_C double pow(double, double);


typedef struct {const char *s; const void **p;} __Pyx_CApiTabEntry; /*proto*/
typedef struct {PyObject **p; char *s;} __Pyx_InternTabEntry; /*proto*/
typedef struct {PyObject **p; char *s; long n;} __Pyx_StringTabEntry; /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
static char **__pyx_f;

static int __Pyx_ArgTypeTest(PyObject *obj, PyTypeObject *type, int none_allowed, char *name); /*proto*/

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static int __Pyx_TypeTest(PyObject *obj, PyTypeObject *type); /*proto*/

static PyObject *__Pyx_UnpackItem(PyObject *); /*proto*/
static int __Pyx_EndUnpack(PyObject *); /*proto*/

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb); /*proto*/

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t); /*proto*/

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/

static void __Pyx_AddTraceback(char *funcname); /*proto*/

/* Declarations from fastgeom */


struct __pyx_obj_8fastgeom_ThreeTuple {
  PyObject_HEAD
  float a;
  float b;
  float c;
};


struct __pyx_obj_8fastgeom_PlueckerLine {
  PyObject_HEAD
  struct __pyx_obj_8fastgeom_ThreeTuple *u;
  struct __pyx_obj_8fastgeom_ThreeTuple *v;
};

static PyTypeObject *__pyx_ptype_8fastgeom_ThreeTuple = 0;
static PyTypeObject *__pyx_ptype_8fastgeom_PlueckerLine = 0;


/* Implementation of fastgeom */

static PyObject *__pyx_n_line_from_points;
static PyObject *__pyx_n_line_from_HZline;

static PyObject *__pyx_n_isinstance;

static int __pyx_f_8fastgeom_10ThreeTuple___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_f_8fastgeom_10ThreeTuple___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_vals = 0;
  struct __pyx_obj_8fastgeom_ThreeTuple *__pyx_v_tt;
  int __pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  int __pyx_4;
  float __pyx_5;
  static char *__pyx_argnames[] = {"vals",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_vals)) return -1;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_vals);
  __pyx_v_tt = ((struct __pyx_obj_8fastgeom_ThreeTuple *)Py_None); Py_INCREF(Py_None);

  /* "/home/astraw/src/kookaburra/flydra/src/fastgeom.pyx":7 */
  __pyx_1 = __Pyx_GetName(__pyx_b, __pyx_n_isinstance); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 7; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(2); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 7; goto __pyx_L1;}
  Py_INCREF(__pyx_v_vals);
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_v_vals);
  Py_INCREF(((PyObject*)__pyx_ptype_8fastgeom_ThreeTuple));
  PyTuple_SET_ITEM(__pyx_2, 1, ((PyObject*)__pyx_ptype_8fastgeom_ThreeTuple));
  __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 7; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_4 = PyObject_IsTrue(__pyx_3); if (__pyx_4 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 7; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  if (__pyx_4) {

    /* "/home/astraw/src/kookaburra/flydra/src/fastgeom.pyx":8 */
    if (!__Pyx_TypeTest(__pyx_v_vals, __pyx_ptype_8fastgeom_ThreeTuple)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 8; goto __pyx_L1;}
    Py_INCREF(__pyx_v_vals);
    Py_DECREF(((PyObject *)__pyx_v_tt));
    __pyx_v_tt = ((struct __pyx_obj_8fastgeom_ThreeTuple *)__pyx_v_vals);

    /* "/home/astraw/src/kookaburra/flydra/src/fastgeom.pyx":9 */
    ((struct __pyx_obj_8fastgeom_ThreeTuple *)__pyx_v_self)->a = __pyx_v_tt->a;

    /* "/home/astraw/src/kookaburra/flydra/src/fastgeom.pyx":10 */
    ((struct __pyx_obj_8fastgeom_ThreeTuple *)__pyx_v_self)->b = __pyx_v_tt->b;

    /* "/home/astraw/src/kookaburra/flydra/src/fastgeom.pyx":11 */
    ((struct __pyx_obj_8fastgeom_ThreeTuple *)__pyx_v_self)->c = __pyx_v_tt->c;

    /* "/home/astraw/src/kookaburra/flydra/src/fastgeom.pyx":12 */
    __pyx_r = 0;
    goto __pyx_L0;
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/home/astraw/src/kookaburra/flydra/src/fastgeom.pyx":13 */
  __pyx_1 = PyObject_GetIter(__pyx_v_vals); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 13; goto __pyx_L1;}
  __pyx_2 = __Pyx_UnpackItem(__pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 13; goto __pyx_L1;}
  __pyx_5 = PyFloat_AsDouble(__pyx_2); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 13; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  ((struct __pyx_obj_8fastgeom_ThreeTuple *)__pyx_v_self)->a = __pyx_5;
  __pyx_3 = __Pyx_UnpackItem(__pyx_1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 13; goto __pyx_L1;}
  __pyx_5 = PyFloat_AsDouble(__pyx_3); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 13; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  ((struct __pyx_obj_8fastgeom_ThreeTuple *)__pyx_v_self)->b = __pyx_5;
  __pyx_2 = __Pyx_UnpackItem(__pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 13; goto __pyx_L1;}
  __pyx_5 = PyFloat_AsDouble(__pyx_2); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 13; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  ((struct __pyx_obj_8fastgeom_ThreeTuple *)__pyx_v_self)->c = __pyx_5;
  if (__Pyx_EndUnpack(__pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 13; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("fastgeom.ThreeTuple.__init__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_tt);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_vals);
  return __pyx_r;
}

static PyObject *__pyx_k1p;

static char (__pyx_k1[]) = "ThreeTuple( (%f,%f,%f))";

static PyObject *__pyx_f_8fastgeom_10ThreeTuple___repr__(PyObject *__pyx_v_self); /*proto*/
static PyObject *__pyx_f_8fastgeom_10ThreeTuple___repr__(PyObject *__pyx_v_self) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  Py_INCREF(__pyx_v_self);

  /* "/home/astraw/src/kookaburra/flydra/src/fastgeom.pyx":15 */
  __pyx_1 = PyFloat_FromDouble(((struct __pyx_obj_8fastgeom_ThreeTuple *)__pyx_v_self)->a); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; goto __pyx_L1;}
  __pyx_2 = PyFloat_FromDouble(((struct __pyx_obj_8fastgeom_ThreeTuple *)__pyx_v_self)->b); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 16; goto __pyx_L1;}
  __pyx_3 = PyFloat_FromDouble(((struct __pyx_obj_8fastgeom_ThreeTuple *)__pyx_v_self)->c); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 17; goto __pyx_L1;}
  __pyx_4 = PyTuple_New(3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_1);
  PyTuple_SET_ITEM(__pyx_4, 1, __pyx_2);
  PyTuple_SET_ITEM(__pyx_4, 2, __pyx_3);
  __pyx_1 = 0;
  __pyx_2 = 0;
  __pyx_3 = 0;
  __pyx_1 = PyNumber_Remainder(__pyx_k1p, __pyx_4); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("fastgeom.ThreeTuple.__repr__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_n___new__;

static PyObject *__pyx_f_8fastgeom_10ThreeTuple___sub__(PyObject *__pyx_v_self, PyObject *__pyx_v_other); /*proto*/
static PyObject *__pyx_f_8fastgeom_10ThreeTuple___sub__(PyObject *__pyx_v_self, PyObject *__pyx_v_other) {
  struct __pyx_obj_8fastgeom_ThreeTuple *__pyx_v_result;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_other);
  __pyx_v_result = ((struct __pyx_obj_8fastgeom_ThreeTuple *)Py_None); Py_INCREF(Py_None);
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_self), __pyx_ptype_8fastgeom_ThreeTuple, 0, "self")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 18; goto __pyx_L1;}
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_other), __pyx_ptype_8fastgeom_ThreeTuple, 0, "other")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 18; goto __pyx_L1;}

  /* "/home/astraw/src/kookaburra/flydra/src/fastgeom.pyx":20 */
  __pyx_1 = PyObject_GetAttr(((PyObject*)__pyx_ptype_8fastgeom_ThreeTuple), __pyx_n___new__); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 20; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 20; goto __pyx_L1;}
  Py_INCREF(((PyObject*)__pyx_ptype_8fastgeom_ThreeTuple));
  PyTuple_SET_ITEM(__pyx_2, 0, ((PyObject*)__pyx_ptype_8fastgeom_ThreeTuple));
  __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 20; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (!__Pyx_TypeTest(__pyx_3, __pyx_ptype_8fastgeom_ThreeTuple)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 20; goto __pyx_L1;}
  Py_DECREF(((PyObject *)__pyx_v_result));
  __pyx_v_result = ((struct __pyx_obj_8fastgeom_ThreeTuple *)__pyx_3);
  __pyx_3 = 0;

  /* "/home/astraw/src/kookaburra/flydra/src/fastgeom.pyx":21 */
  __pyx_v_result->a = (((struct __pyx_obj_8fastgeom_ThreeTuple *)__pyx_v_self)->a - ((struct __pyx_obj_8fastgeom_ThreeTuple *)__pyx_v_other)->a);

  /* "/home/astraw/src/kookaburra/flydra/src/fastgeom.pyx":22 */
  __pyx_v_result->b = (((struct __pyx_obj_8fastgeom_ThreeTuple *)__pyx_v_self)->b - ((struct __pyx_obj_8fastgeom_ThreeTuple *)__pyx_v_other)->b);

  /* "/home/astraw/src/kookaburra/flydra/src/fastgeom.pyx":23 */
  __pyx_v_result->c = (((struct __pyx_obj_8fastgeom_ThreeTuple *)__pyx_v_self)->c - ((struct __pyx_obj_8fastgeom_ThreeTuple *)__pyx_v_other)->c);

  /* "/home/astraw/src/kookaburra/flydra/src/fastgeom.pyx":24 */
  Py_INCREF(((PyObject *)__pyx_v_result));
  __pyx_r = ((PyObject *)__pyx_v_result);
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("fastgeom.ThreeTuple.__sub__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_result);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_other);
  return __pyx_r;
}

static PyObject *__pyx_f_8fastgeom_10ThreeTuple___add__(PyObject *__pyx_v_self, PyObject *__pyx_v_other); /*proto*/
static PyObject *__pyx_f_8fastgeom_10ThreeTuple___add__(PyObject *__pyx_v_self, PyObject *__pyx_v_other) {
  struct __pyx_obj_8fastgeom_ThreeTuple *__pyx_v_result;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_other);
  __pyx_v_result = ((struct __pyx_obj_8fastgeom_ThreeTuple *)Py_None); Py_INCREF(Py_None);
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_self), __pyx_ptype_8fastgeom_ThreeTuple, 0, "self")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 26; goto __pyx_L1;}
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_other), __pyx_ptype_8fastgeom_ThreeTuple, 0, "other")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 26; goto __pyx_L1;}

  /* "/home/astraw/src/kookaburra/flydra/src/fastgeom.pyx":28 */
  __pyx_1 = PyObject_GetAttr(((PyObject*)__pyx_ptype_8fastgeom_ThreeTuple), __pyx_n___new__); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 28; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 28; goto __pyx_L1;}
  Py_INCREF(((PyObject*)__pyx_ptype_8fastgeom_ThreeTuple));
  PyTuple_SET_ITEM(__pyx_2, 0, ((PyObject*)__pyx_ptype_8fastgeom_ThreeTuple));
  __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 28; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (!__Pyx_TypeTest(__pyx_3, __pyx_ptype_8fastgeom_ThreeTuple)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 28; goto __pyx_L1;}
  Py_DECREF(((PyObject *)__pyx_v_result));
  __pyx_v_result = ((struct __pyx_obj_8fastgeom_ThreeTuple *)__pyx_3);
  __pyx_3 = 0;

  /* "/home/astraw/src/kookaburra/flydra/src/fastgeom.pyx":29 */
  __pyx_v_result->a = (((struct __pyx_obj_8fastgeom_ThreeTuple *)__pyx_v_self)->a + ((struct __pyx_obj_8fastgeom_ThreeTuple *)__pyx_v_other)->a);

  /* "/home/astraw/src/kookaburra/flydra/src/fastgeom.pyx":30 */
  __pyx_v_result->b = (((struct __pyx_obj_8fastgeom_ThreeTuple *)__pyx_v_self)->b + ((struct __pyx_obj_8fastgeom_ThreeTuple *)__pyx_v_other)->b);

  /* "/home/astraw/src/kookaburra/flydra/src/fastgeom.pyx":31 */
  __pyx_v_result->c = (((struct __pyx_obj_8fastgeom_ThreeTuple *)__pyx_v_self)->c + ((struct __pyx_obj_8fastgeom_ThreeTuple *)__pyx_v_other)->c);

  /* "/home/astraw/src/kookaburra/flydra/src/fastgeom.pyx":32 */
  Py_INCREF(((PyObject *)__pyx_v_result));
  __pyx_r = ((PyObject *)__pyx_v_result);
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("fastgeom.ThreeTuple.__add__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_result);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_other);
  return __pyx_r;
}

static PyObject *__pyx_n_True;
static PyObject *__pyx_n_False;
static PyObject *__pyx_n_NotImplementedError;

static PyObject *__pyx_k2p;

static char (__pyx_k2[]) = "this comparison not supported";

static PyObject *__pyx_f_8fastgeom_10ThreeTuple___richcmp__(PyObject *__pyx_v_x, PyObject *__pyx_v_y, int __pyx_v_op); /*proto*/
static PyObject *__pyx_f_8fastgeom_10ThreeTuple___richcmp__(PyObject *__pyx_v_x, PyObject *__pyx_v_y, int __pyx_v_op) {
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  Py_INCREF(__pyx_v_x);
  Py_INCREF(__pyx_v_y);
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_x), __pyx_ptype_8fastgeom_ThreeTuple, 0, "x")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 34; goto __pyx_L1;}
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_y), __pyx_ptype_8fastgeom_ThreeTuple, 0, "y")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 35; goto __pyx_L1;}

  /* "/home/astraw/src/kookaburra/flydra/src/fastgeom.pyx":37 */
  __pyx_1 = (__pyx_v_op == 2);
  if (__pyx_1) {

    /* "/home/astraw/src/kookaburra/flydra/src/fastgeom.pyx":38 */
    __pyx_1 = (((struct __pyx_obj_8fastgeom_ThreeTuple *)__pyx_v_x)->a == ((struct __pyx_obj_8fastgeom_ThreeTuple *)__pyx_v_y)->a);
    if (__pyx_1) {
      __pyx_1 = (((struct __pyx_obj_8fastgeom_ThreeTuple *)__pyx_v_x)->b == ((struct __pyx_obj_8fastgeom_ThreeTuple *)__pyx_v_y)->b);
      if (__pyx_1) {
        __pyx_1 = (((struct __pyx_obj_8fastgeom_ThreeTuple *)__pyx_v_x)->c == ((struct __pyx_obj_8fastgeom_ThreeTuple *)__pyx_v_y)->c);
      }
    }
    if (__pyx_1) {

      /* "/home/astraw/src/kookaburra/flydra/src/fastgeom.pyx":41 */
      __pyx_2 = __Pyx_GetName(__pyx_b, __pyx_n_True); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 41; goto __pyx_L1;}
      __pyx_r = __pyx_2;
      __pyx_2 = 0;
      goto __pyx_L0;
      goto __pyx_L3;
    }
    /*else*/ {

      /* "/home/astraw/src/kookaburra/flydra/src/fastgeom.pyx":43 */
      __pyx_2 = __Pyx_GetName(__pyx_b, __pyx_n_False); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 43; goto __pyx_L1;}
      __pyx_r = __pyx_2;
      __pyx_2 = 0;
      goto __pyx_L0;
    }
    __pyx_L3:;
    goto __pyx_L2;
  }
  /*else*/ {

    /* "/home/astraw/src/kookaburra/flydra/src/fastgeom.pyx":45 */
    __pyx_2 = __Pyx_GetName(__pyx_b, __pyx_n_NotImplementedError); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; goto __pyx_L1;}
    __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; goto __pyx_L1;}
    Py_INCREF(__pyx_k2p);
    PyTuple_SET_ITEM(__pyx_3, 0, __pyx_k2p);
    __pyx_4 = PyObject_CallObject(__pyx_2, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __Pyx_Raise(__pyx_4, 0, 0);
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; goto __pyx_L1;}
  }
  __pyx_L2:;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("fastgeom.ThreeTuple.__richcmp__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_x);
  Py_DECREF(__pyx_v_y);
  return __pyx_r;
}

static PyObject *__pyx_f_8fastgeom_10ThreeTuple___neg__(PyObject *__pyx_v_self); /*proto*/
static PyObject *__pyx_f_8fastgeom_10ThreeTuple___neg__(PyObject *__pyx_v_self) {
  struct __pyx_obj_8fastgeom_ThreeTuple *__pyx_v_result;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  Py_INCREF(__pyx_v_self);
  __pyx_v_result = ((struct __pyx_obj_8fastgeom_ThreeTuple *)Py_None); Py_INCREF(Py_None);

  /* "/home/astraw/src/kookaburra/flydra/src/fastgeom.pyx":49 */
  __pyx_1 = PyObject_GetAttr(((PyObject*)__pyx_ptype_8fastgeom_ThreeTuple), __pyx_n___new__); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 49; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 49; goto __pyx_L1;}
  Py_INCREF(((PyObject*)__pyx_ptype_8fastgeom_ThreeTuple));
  PyTuple_SET_ITEM(__pyx_2, 0, ((PyObject*)__pyx_ptype_8fastgeom_ThreeTuple));
  __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 49; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (!__Pyx_TypeTest(__pyx_3, __pyx_ptype_8fastgeom_ThreeTuple)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 49; goto __pyx_L1;}
  Py_DECREF(((PyObject *)__pyx_v_result));
  __pyx_v_result = ((struct __pyx_obj_8fastgeom_ThreeTuple *)__pyx_3);
  __pyx_3 = 0;

  /* "/home/astraw/src/kookaburra/flydra/src/fastgeom.pyx":50 */
  __pyx_v_result->a = (-((struct __pyx_obj_8fastgeom_ThreeTuple *)__pyx_v_self)->a);

  /* "/home/astraw/src/kookaburra/flydra/src/fastgeom.pyx":51 */
  __pyx_v_result->b = (-((struct __pyx_obj_8fastgeom_ThreeTuple *)__pyx_v_self)->b);

  /* "/home/astraw/src/kookaburra/flydra/src/fastgeom.pyx":52 */
  __pyx_v_result->c = (-((struct __pyx_obj_8fastgeom_ThreeTuple *)__pyx_v_self)->c);

  /* "/home/astraw/src/kookaburra/flydra/src/fastgeom.pyx":53 */
  Py_INCREF(((PyObject *)__pyx_v_result));
  __pyx_r = ((PyObject *)__pyx_v_result);
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("fastgeom.ThreeTuple.__neg__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_result);
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_8fastgeom_10ThreeTuple_cross(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_8fastgeom_10ThreeTuple_cross(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  struct __pyx_obj_8fastgeom_ThreeTuple *__pyx_v_other = 0;
  struct __pyx_obj_8fastgeom_ThreeTuple *__pyx_v_result;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  static char *__pyx_argnames[] = {"other",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_other)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_other);
  __pyx_v_result = ((struct __pyx_obj_8fastgeom_ThreeTuple *)Py_None); Py_INCREF(Py_None);
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_other), __pyx_ptype_8fastgeom_ThreeTuple, 0, "other")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 55; goto __pyx_L1;}

  /* "/home/astraw/src/kookaburra/flydra/src/fastgeom.pyx":58 */
  __pyx_1 = PyObject_GetAttr(((PyObject*)__pyx_ptype_8fastgeom_ThreeTuple), __pyx_n___new__); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; goto __pyx_L1;}
  Py_INCREF(((PyObject*)__pyx_ptype_8fastgeom_ThreeTuple));
  PyTuple_SET_ITEM(__pyx_2, 0, ((PyObject*)__pyx_ptype_8fastgeom_ThreeTuple));
  __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (!__Pyx_TypeTest(__pyx_3, __pyx_ptype_8fastgeom_ThreeTuple)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; goto __pyx_L1;}
  Py_DECREF(((PyObject *)__pyx_v_result));
  __pyx_v_result = ((struct __pyx_obj_8fastgeom_ThreeTuple *)__pyx_3);
  __pyx_3 = 0;

  /* "/home/astraw/src/kookaburra/flydra/src/fastgeom.pyx":59 */
  __pyx_v_result->a = ((((struct __pyx_obj_8fastgeom_ThreeTuple *)__pyx_v_self)->b * __pyx_v_other->c) - (((struct __pyx_obj_8fastgeom_ThreeTuple *)__pyx_v_self)->c * __pyx_v_other->b));

  /* "/home/astraw/src/kookaburra/flydra/src/fastgeom.pyx":60 */
  __pyx_v_result->b = ((((struct __pyx_obj_8fastgeom_ThreeTuple *)__pyx_v_self)->c * __pyx_v_other->a) - (((struct __pyx_obj_8fastgeom_ThreeTuple *)__pyx_v_self)->a * __pyx_v_other->c));

  /* "/home/astraw/src/kookaburra/flydra/src/fastgeom.pyx":61 */
  __pyx_v_result->c = ((((struct __pyx_obj_8fastgeom_ThreeTuple *)__pyx_v_self)->a * __pyx_v_other->b) - (((struct __pyx_obj_8fastgeom_ThreeTuple *)__pyx_v_self)->b * __pyx_v_other->a));

  /* "/home/astraw/src/kookaburra/flydra/src/fastgeom.pyx":62 */
  Py_INCREF(((PyObject *)__pyx_v_result));
  __pyx_r = ((PyObject *)__pyx_v_result);
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("fastgeom.ThreeTuple.cross");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_result);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_other);
  return __pyx_r;
}

static PyObject *__pyx_f_8fastgeom_10ThreeTuple_dot(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_8fastgeom_10ThreeTuple_dot(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  struct __pyx_obj_8fastgeom_ThreeTuple *__pyx_v_other = 0;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {"other",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_other)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_other);
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_other), __pyx_ptype_8fastgeom_ThreeTuple, 0, "other")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; goto __pyx_L1;}

  /* "/home/astraw/src/kookaburra/flydra/src/fastgeom.pyx":65 */
  __pyx_1 = PyFloat_FromDouble((((((struct __pyx_obj_8fastgeom_ThreeTuple *)__pyx_v_self)->a * __pyx_v_other->a) + (((struct __pyx_obj_8fastgeom_ThreeTuple *)__pyx_v_self)->b * __pyx_v_other->b)) + (((struct __pyx_obj_8fastgeom_ThreeTuple *)__pyx_v_self)->c * __pyx_v_other->c))); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 65; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("fastgeom.ThreeTuple.dot");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_other);
  return __pyx_r;
}

static int __pyx_f_8fastgeom_12PlueckerLine___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_f_8fastgeom_12PlueckerLine___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  struct __pyx_obj_8fastgeom_ThreeTuple *__pyx_v_u_ = 0;
  struct __pyx_obj_8fastgeom_ThreeTuple *__pyx_v_v_ = 0;
  int __pyx_r;
  static char *__pyx_argnames[] = {"u_","v_",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OO", __pyx_argnames, &__pyx_v_u_, &__pyx_v_v_)) return -1;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_u_);
  Py_INCREF(__pyx_v_v_);
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_u_), __pyx_ptype_8fastgeom_ThreeTuple, 0, "u_")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 70; goto __pyx_L1;}
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_v_), __pyx_ptype_8fastgeom_ThreeTuple, 0, "v_")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 70; goto __pyx_L1;}

  /* "/home/astraw/src/kookaburra/flydra/src/fastgeom.pyx":71 */
  Py_INCREF(((PyObject *)__pyx_v_u_));
  Py_DECREF(((PyObject *)((struct __pyx_obj_8fastgeom_PlueckerLine *)__pyx_v_self)->u));
  ((struct __pyx_obj_8fastgeom_PlueckerLine *)__pyx_v_self)->u = __pyx_v_u_;

  /* "/home/astraw/src/kookaburra/flydra/src/fastgeom.pyx":72 */
  Py_INCREF(((PyObject *)__pyx_v_v_));
  Py_DECREF(((PyObject *)((struct __pyx_obj_8fastgeom_PlueckerLine *)__pyx_v_self)->v));
  ((struct __pyx_obj_8fastgeom_PlueckerLine *)__pyx_v_self)->v = __pyx_v_v_;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("fastgeom.PlueckerLine.__init__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_u_);
  Py_DECREF(__pyx_v_v_);
  return __pyx_r;
}

static PyObject *__pyx_n_repr;

static PyObject *__pyx_k3p;

static char (__pyx_k3[]) = "PlueckerLine(%s,%s)";

static PyObject *__pyx_f_8fastgeom_12PlueckerLine___repr__(PyObject *__pyx_v_self); /*proto*/
static PyObject *__pyx_f_8fastgeom_12PlueckerLine___repr__(PyObject *__pyx_v_self) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  Py_INCREF(__pyx_v_self);

  /* "/home/astraw/src/kookaburra/flydra/src/fastgeom.pyx":74 */
  __pyx_1 = __Pyx_GetName(__pyx_b, __pyx_n_repr); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 74; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 74; goto __pyx_L1;}
  Py_INCREF(((PyObject *)((struct __pyx_obj_8fastgeom_PlueckerLine *)__pyx_v_self)->u));
  PyTuple_SET_ITEM(__pyx_2, 0, ((PyObject *)((struct __pyx_obj_8fastgeom_PlueckerLine *)__pyx_v_self)->u));
  __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 74; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_1 = __Pyx_GetName(__pyx_b, __pyx_n_repr); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 74; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 74; goto __pyx_L1;}
  Py_INCREF(((PyObject *)((struct __pyx_obj_8fastgeom_PlueckerLine *)__pyx_v_self)->v));
  PyTuple_SET_ITEM(__pyx_2, 0, ((PyObject *)((struct __pyx_obj_8fastgeom_PlueckerLine *)__pyx_v_self)->v));
  __pyx_4 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 74; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_1 = PyTuple_New(2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 74; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_1, 0, __pyx_3);
  PyTuple_SET_ITEM(__pyx_1, 1, __pyx_4);
  __pyx_3 = 0;
  __pyx_4 = 0;
  __pyx_2 = PyNumber_Remainder(__pyx_k3p, __pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 74; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("fastgeom.PlueckerLine.__repr__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_k4p;

static char (__pyx_k4[]) = "this comparison not supported";

static PyObject *__pyx_f_8fastgeom_12PlueckerLine___richcmp__(PyObject *__pyx_v_x, PyObject *__pyx_v_y, int __pyx_v_op); /*proto*/
static PyObject *__pyx_f_8fastgeom_12PlueckerLine___richcmp__(PyObject *__pyx_v_x, PyObject *__pyx_v_y, int __pyx_v_op) {
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  Py_INCREF(__pyx_v_x);
  Py_INCREF(__pyx_v_y);
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_x), __pyx_ptype_8fastgeom_PlueckerLine, 0, "x")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 76; goto __pyx_L1;}
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_y), __pyx_ptype_8fastgeom_PlueckerLine, 0, "y")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 77; goto __pyx_L1;}

  /* "/home/astraw/src/kookaburra/flydra/src/fastgeom.pyx":79 */
  __pyx_1 = (__pyx_v_op == 2);
  if (__pyx_1) {

    /* "/home/astraw/src/kookaburra/flydra/src/fastgeom.pyx":80 */
    if (PyObject_Cmp(((PyObject *)((struct __pyx_obj_8fastgeom_PlueckerLine *)__pyx_v_x)->u), ((PyObject *)((struct __pyx_obj_8fastgeom_PlueckerLine *)__pyx_v_y)->u), &__pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 80; goto __pyx_L1;}
    __pyx_1 = __pyx_1 == 0;
    if (__pyx_1) {
      if (PyObject_Cmp(((PyObject *)((struct __pyx_obj_8fastgeom_PlueckerLine *)__pyx_v_x)->v), ((PyObject *)((struct __pyx_obj_8fastgeom_PlueckerLine *)__pyx_v_y)->v), &__pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 81; goto __pyx_L1;}
      __pyx_1 = __pyx_1 == 0;
    }
    if (__pyx_1) {

      /* "/home/astraw/src/kookaburra/flydra/src/fastgeom.pyx":82 */
      __pyx_2 = __Pyx_GetName(__pyx_b, __pyx_n_True); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 82; goto __pyx_L1;}
      __pyx_r = __pyx_2;
      __pyx_2 = 0;
      goto __pyx_L0;
      goto __pyx_L3;
    }
    /*else*/ {

      /* "/home/astraw/src/kookaburra/flydra/src/fastgeom.pyx":84 */
      __pyx_2 = __Pyx_GetName(__pyx_b, __pyx_n_False); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 84; goto __pyx_L1;}
      __pyx_r = __pyx_2;
      __pyx_2 = 0;
      goto __pyx_L0;
    }
    __pyx_L3:;
    goto __pyx_L2;
  }
  /*else*/ {

    /* "/home/astraw/src/kookaburra/flydra/src/fastgeom.pyx":86 */
    __pyx_2 = __Pyx_GetName(__pyx_b, __pyx_n_NotImplementedError); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 86; goto __pyx_L1;}
    __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 86; goto __pyx_L1;}
    Py_INCREF(__pyx_k4p);
    PyTuple_SET_ITEM(__pyx_3, 0, __pyx_k4p);
    __pyx_4 = PyObject_CallObject(__pyx_2, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 86; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __Pyx_Raise(__pyx_4, 0, 0);
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 86; goto __pyx_L1;}
  }
  __pyx_L2:;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("fastgeom.PlueckerLine.__richcmp__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_x);
  Py_DECREF(__pyx_v_y);
  return __pyx_r;
}

static PyObject *__pyx_n_cross;
static PyObject *__pyx_n_dot;

static PyObject *__pyx_f_8fastgeom_12PlueckerLine_closest(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_8fastgeom_12PlueckerLine_closest(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  struct __pyx_obj_8fastgeom_ThreeTuple *__pyx_v_VxU;
  float __pyx_v_UdotU;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  float __pyx_4;
  PyObject *__pyx_5 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);
  __pyx_v_VxU = ((struct __pyx_obj_8fastgeom_ThreeTuple *)Py_None); Py_INCREF(Py_None);

  /* "/home/astraw/src/kookaburra/flydra/src/fastgeom.pyx":91 */
  __pyx_1 = PyObject_GetAttr(((PyObject *)((struct __pyx_obj_8fastgeom_PlueckerLine *)__pyx_v_self)->v), __pyx_n_cross); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; goto __pyx_L1;}
  Py_INCREF(((PyObject *)((struct __pyx_obj_8fastgeom_PlueckerLine *)__pyx_v_self)->u));
  PyTuple_SET_ITEM(__pyx_2, 0, ((PyObject *)((struct __pyx_obj_8fastgeom_PlueckerLine *)__pyx_v_self)->u));
  __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (!__Pyx_TypeTest(__pyx_3, __pyx_ptype_8fastgeom_ThreeTuple)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; goto __pyx_L1;}
  Py_DECREF(((PyObject *)__pyx_v_VxU));
  __pyx_v_VxU = ((struct __pyx_obj_8fastgeom_ThreeTuple *)__pyx_3);
  __pyx_3 = 0;

  /* "/home/astraw/src/kookaburra/flydra/src/fastgeom.pyx":92 */
  __pyx_1 = PyObject_GetAttr(((PyObject *)((struct __pyx_obj_8fastgeom_PlueckerLine *)__pyx_v_self)->u), __pyx_n_dot); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; goto __pyx_L1;}
  Py_INCREF(((PyObject *)((struct __pyx_obj_8fastgeom_PlueckerLine *)__pyx_v_self)->u));
  PyTuple_SET_ITEM(__pyx_2, 0, ((PyObject *)((struct __pyx_obj_8fastgeom_PlueckerLine *)__pyx_v_self)->u));
  __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_4 = PyFloat_AsDouble(__pyx_3); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_v_UdotU = __pyx_4;

  /* "/home/astraw/src/kookaburra/flydra/src/fastgeom.pyx":93 */
  __pyx_1 = PyFloat_FromDouble((__pyx_v_VxU->a / __pyx_v_UdotU)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 93; goto __pyx_L1;}
  __pyx_2 = PyFloat_FromDouble((__pyx_v_VxU->b / __pyx_v_UdotU)); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; goto __pyx_L1;}
  __pyx_3 = PyFloat_FromDouble((__pyx_v_VxU->c / __pyx_v_UdotU)); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; goto __pyx_L1;}
  __pyx_5 = PyTuple_New(3); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 93; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_5, 0, __pyx_1);
  PyTuple_SET_ITEM(__pyx_5, 1, __pyx_2);
  PyTuple_SET_ITEM(__pyx_5, 2, __pyx_3);
  __pyx_1 = 0;
  __pyx_2 = 0;
  __pyx_3 = 0;
  __pyx_1 = PyTuple_New(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 93; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_1, 0, __pyx_5);
  __pyx_5 = 0;
  __pyx_2 = PyObject_CallObject(((PyObject*)__pyx_ptype_8fastgeom_ThreeTuple), __pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 93; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("fastgeom.PlueckerLine.closest");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_VxU);
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_8fastgeom_12PlueckerLine_dist2(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_8fastgeom_12PlueckerLine_dist2(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/home/astraw/src/kookaburra/flydra/src/fastgeom.pyx":97 */
  __pyx_1 = PyObject_GetAttr(((PyObject *)((struct __pyx_obj_8fastgeom_PlueckerLine *)__pyx_v_self)->v), __pyx_n_dot); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 97; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 97; goto __pyx_L1;}
  Py_INCREF(((PyObject *)((struct __pyx_obj_8fastgeom_PlueckerLine *)__pyx_v_self)->v));
  PyTuple_SET_ITEM(__pyx_2, 0, ((PyObject *)((struct __pyx_obj_8fastgeom_PlueckerLine *)__pyx_v_self)->v));
  __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 97; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_1 = PyObject_GetAttr(((PyObject *)((struct __pyx_obj_8fastgeom_PlueckerLine *)__pyx_v_self)->u), __pyx_n_dot); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 97; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 97; goto __pyx_L1;}
  Py_INCREF(((PyObject *)((struct __pyx_obj_8fastgeom_PlueckerLine *)__pyx_v_self)->u));
  PyTuple_SET_ITEM(__pyx_2, 0, ((PyObject *)((struct __pyx_obj_8fastgeom_PlueckerLine *)__pyx_v_self)->u));
  __pyx_4 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 97; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_1 = PyNumber_Divide(__pyx_3, __pyx_4); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 97; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("fastgeom.PlueckerLine.dist2");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_n_closest;

static PyObject *__pyx_f_8fastgeom_12PlueckerLine_translate(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_8fastgeom_12PlueckerLine_translate(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  struct __pyx_obj_8fastgeom_ThreeTuple *__pyx_v_x = 0;
  struct __pyx_obj_8fastgeom_ThreeTuple *__pyx_v_on_line;
  struct __pyx_obj_8fastgeom_ThreeTuple *__pyx_v_on_new_line_a;
  struct __pyx_obj_8fastgeom_ThreeTuple *__pyx_v_on_new_line_b;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  static char *__pyx_argnames[] = {"x",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_x)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_x);
  __pyx_v_on_line = ((struct __pyx_obj_8fastgeom_ThreeTuple *)Py_None); Py_INCREF(Py_None);
  __pyx_v_on_new_line_a = ((struct __pyx_obj_8fastgeom_ThreeTuple *)Py_None); Py_INCREF(Py_None);
  __pyx_v_on_new_line_b = ((struct __pyx_obj_8fastgeom_ThreeTuple *)Py_None); Py_INCREF(Py_None);
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_x), __pyx_ptype_8fastgeom_ThreeTuple, 0, "x")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 99; goto __pyx_L1;}

  /* "/home/astraw/src/kookaburra/flydra/src/fastgeom.pyx":104 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_self, __pyx_n_closest); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 104; goto __pyx_L1;}
  __pyx_2 = PyObject_CallObject(__pyx_1, 0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 104; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  if (!__Pyx_TypeTest(__pyx_2, __pyx_ptype_8fastgeom_ThreeTuple)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 104; goto __pyx_L1;}
  Py_DECREF(((PyObject *)__pyx_v_on_line));
  __pyx_v_on_line = ((struct __pyx_obj_8fastgeom_ThreeTuple *)__pyx_2);
  __pyx_2 = 0;

  /* "/home/astraw/src/kookaburra/flydra/src/fastgeom.pyx":105 */
  __pyx_1 = PyNumber_Add(((PyObject *)__pyx_v_on_line), ((PyObject *)__pyx_v_x)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 105; goto __pyx_L1;}
  if (!__Pyx_TypeTest(__pyx_1, __pyx_ptype_8fastgeom_ThreeTuple)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 105; goto __pyx_L1;}
  Py_DECREF(((PyObject *)__pyx_v_on_new_line_a));
  __pyx_v_on_new_line_a = ((struct __pyx_obj_8fastgeom_ThreeTuple *)__pyx_1);
  __pyx_1 = 0;

  /* "/home/astraw/src/kookaburra/flydra/src/fastgeom.pyx":106 */
  __pyx_2 = PyNumber_Add(((PyObject *)__pyx_v_on_new_line_a), ((PyObject *)((struct __pyx_obj_8fastgeom_PlueckerLine *)__pyx_v_self)->u)); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 106; goto __pyx_L1;}
  if (!__Pyx_TypeTest(__pyx_2, __pyx_ptype_8fastgeom_ThreeTuple)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 106; goto __pyx_L1;}
  Py_DECREF(((PyObject *)__pyx_v_on_new_line_b));
  __pyx_v_on_new_line_b = ((struct __pyx_obj_8fastgeom_ThreeTuple *)__pyx_2);
  __pyx_2 = 0;

  /* "/home/astraw/src/kookaburra/flydra/src/fastgeom.pyx":107 */
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_line_from_points); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 107; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(2); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 107; goto __pyx_L1;}
  Py_INCREF(((PyObject *)__pyx_v_on_new_line_a));
  PyTuple_SET_ITEM(__pyx_2, 0, ((PyObject *)__pyx_v_on_new_line_a));
  Py_INCREF(((PyObject *)__pyx_v_on_new_line_b));
  PyTuple_SET_ITEM(__pyx_2, 1, ((PyObject *)__pyx_v_on_new_line_b));
  __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 107; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_r = __pyx_3;
  __pyx_3 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("fastgeom.PlueckerLine.translate");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_on_line);
  Py_DECREF(__pyx_v_on_new_line_a);
  Py_DECREF(__pyx_v_on_new_line_b);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_x);
  return __pyx_r;
}

static PyObject *__pyx_f_8fastgeom_line_from_points(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_8fastgeom_line_from_points(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  struct __pyx_obj_8fastgeom_ThreeTuple *__pyx_v_p = 0;
  struct __pyx_obj_8fastgeom_ThreeTuple *__pyx_v_q = 0;
  struct __pyx_obj_8fastgeom_PlueckerLine *__pyx_v_result;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  static char *__pyx_argnames[] = {"p","q",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OO", __pyx_argnames, &__pyx_v_p, &__pyx_v_q)) return 0;
  Py_INCREF(__pyx_v_p);
  Py_INCREF(__pyx_v_q);
  __pyx_v_result = ((struct __pyx_obj_8fastgeom_PlueckerLine *)Py_None); Py_INCREF(Py_None);
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_p), __pyx_ptype_8fastgeom_ThreeTuple, 0, "p")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 109; goto __pyx_L1;}
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_q), __pyx_ptype_8fastgeom_ThreeTuple, 0, "q")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 109; goto __pyx_L1;}

  /* "/home/astraw/src/kookaburra/flydra/src/fastgeom.pyx":111 */
  __pyx_1 = PyObject_GetAttr(((PyObject*)__pyx_ptype_8fastgeom_PlueckerLine), __pyx_n___new__); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 111; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 111; goto __pyx_L1;}
  Py_INCREF(((PyObject*)__pyx_ptype_8fastgeom_PlueckerLine));
  PyTuple_SET_ITEM(__pyx_2, 0, ((PyObject*)__pyx_ptype_8fastgeom_PlueckerLine));
  __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 111; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (!__Pyx_TypeTest(__pyx_3, __pyx_ptype_8fastgeom_PlueckerLine)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 111; goto __pyx_L1;}
  Py_DECREF(((PyObject *)__pyx_v_result));
  __pyx_v_result = ((struct __pyx_obj_8fastgeom_PlueckerLine *)__pyx_3);
  __pyx_3 = 0;

  /* "/home/astraw/src/kookaburra/flydra/src/fastgeom.pyx":112 */
  __pyx_1 = PyNumber_Subtract(((PyObject *)__pyx_v_p), ((PyObject *)__pyx_v_q)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 112; goto __pyx_L1;}
  if (!__Pyx_TypeTest(__pyx_1, __pyx_ptype_8fastgeom_ThreeTuple)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 112; goto __pyx_L1;}
  Py_DECREF(((PyObject *)__pyx_v_result->u));
  __pyx_v_result->u = ((struct __pyx_obj_8fastgeom_ThreeTuple *)__pyx_1);
  __pyx_1 = 0;

  /* "/home/astraw/src/kookaburra/flydra/src/fastgeom.pyx":113 */
  __pyx_2 = PyObject_GetAttr(((PyObject *)__pyx_v_p), __pyx_n_cross); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 113; goto __pyx_L1;}
  __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 113; goto __pyx_L1;}
  Py_INCREF(((PyObject *)__pyx_v_q));
  PyTuple_SET_ITEM(__pyx_3, 0, ((PyObject *)__pyx_v_q));
  __pyx_1 = PyObject_CallObject(__pyx_2, __pyx_3); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 113; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  if (!__Pyx_TypeTest(__pyx_1, __pyx_ptype_8fastgeom_ThreeTuple)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 113; goto __pyx_L1;}
  Py_DECREF(((PyObject *)__pyx_v_result->v));
  __pyx_v_result->v = ((struct __pyx_obj_8fastgeom_ThreeTuple *)__pyx_1);
  __pyx_1 = 0;

  /* "/home/astraw/src/kookaburra/flydra/src/fastgeom.pyx":114 */
  Py_INCREF(((PyObject *)__pyx_v_result));
  __pyx_r = ((PyObject *)__pyx_v_result);
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("fastgeom.line_from_points");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_result);
  Py_DECREF(__pyx_v_p);
  Py_DECREF(__pyx_v_q);
  return __pyx_r;
}

static PyObject *__pyx_f_8fastgeom_line_from_HZline(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_8fastgeom_line_from_HZline(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_P = 0;
  PyObject *__pyx_v_u;
  PyObject *__pyx_v_v;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  static char *__pyx_argnames[] = {"P",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_P)) return 0;
  Py_INCREF(__pyx_v_P);
  __pyx_v_u = Py_None; Py_INCREF(Py_None);
  __pyx_v_v = Py_None; Py_INCREF(Py_None);

  /* "/home/astraw/src/kookaburra/flydra/src/fastgeom.pyx":117 */
  __pyx_1 = PyInt_FromLong(2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 117; goto __pyx_L1;}
  __pyx_2 = PyObject_GetItem(__pyx_v_P, __pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 117; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyInt_FromLong(4); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 117; goto __pyx_L1;}
  __pyx_3 = PyObject_GetItem(__pyx_v_P, __pyx_1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 117; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyNumber_Negative(__pyx_3); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 117; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_3 = PyInt_FromLong(5); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 117; goto __pyx_L1;}
  __pyx_4 = PyObject_GetItem(__pyx_v_P, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 117; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_3 = PyTuple_New(3); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 117; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_2);
  PyTuple_SET_ITEM(__pyx_3, 1, __pyx_1);
  PyTuple_SET_ITEM(__pyx_3, 2, __pyx_4);
  __pyx_2 = 0;
  __pyx_1 = 0;
  __pyx_4 = 0;
  __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 117; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_3);
  __pyx_3 = 0;
  __pyx_1 = PyObject_CallObject(((PyObject*)__pyx_ptype_8fastgeom_ThreeTuple), __pyx_2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 117; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_v_u);
  __pyx_v_u = __pyx_1;
  __pyx_1 = 0;

  /* "/home/astraw/src/kookaburra/flydra/src/fastgeom.pyx":118 */
  __pyx_4 = PyInt_FromLong(3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 118; goto __pyx_L1;}
  __pyx_3 = PyObject_GetItem(__pyx_v_P, __pyx_4); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 118; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_2 = PyInt_FromLong(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 118; goto __pyx_L1;}
  __pyx_1 = PyObject_GetItem(__pyx_v_P, __pyx_2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 118; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_4 = PyNumber_Negative(__pyx_1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 118; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_2 = PyInt_FromLong(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 118; goto __pyx_L1;}
  __pyx_1 = PyObject_GetItem(__pyx_v_P, __pyx_2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 118; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_2 = PyTuple_New(3); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 118; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_3);
  PyTuple_SET_ITEM(__pyx_2, 1, __pyx_4);
  PyTuple_SET_ITEM(__pyx_2, 2, __pyx_1);
  __pyx_3 = 0;
  __pyx_4 = 0;
  __pyx_1 = 0;
  __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 118; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_2);
  __pyx_2 = 0;
  __pyx_4 = PyObject_CallObject(((PyObject*)__pyx_ptype_8fastgeom_ThreeTuple), __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 118; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_v_v);
  __pyx_v_v = __pyx_4;
  __pyx_4 = 0;

  /* "/home/astraw/src/kookaburra/flydra/src/fastgeom.pyx":119 */
  __pyx_1 = PyTuple_New(2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 119; goto __pyx_L1;}
  Py_INCREF(__pyx_v_u);
  PyTuple_SET_ITEM(__pyx_1, 0, __pyx_v_u);
  Py_INCREF(__pyx_v_v);
  PyTuple_SET_ITEM(__pyx_1, 1, __pyx_v_v);
  __pyx_2 = PyObject_CallObject(((PyObject*)__pyx_ptype_8fastgeom_PlueckerLine), __pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 119; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("fastgeom.line_from_HZline");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_u);
  Py_DECREF(__pyx_v_v);
  Py_DECREF(__pyx_v_P);
  return __pyx_r;
}

static __Pyx_InternTabEntry __pyx_intern_tab[] = {
  {&__pyx_n_False, "False"},
  {&__pyx_n_NotImplementedError, "NotImplementedError"},
  {&__pyx_n_True, "True"},
  {&__pyx_n___new__, "__new__"},
  {&__pyx_n_closest, "closest"},
  {&__pyx_n_cross, "cross"},
  {&__pyx_n_dot, "dot"},
  {&__pyx_n_isinstance, "isinstance"},
  {&__pyx_n_line_from_HZline, "line_from_HZline"},
  {&__pyx_n_line_from_points, "line_from_points"},
  {&__pyx_n_repr, "repr"},
  {0, 0}
};

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_k1p, __pyx_k1, sizeof(__pyx_k1)},
  {&__pyx_k2p, __pyx_k2, sizeof(__pyx_k2)},
  {&__pyx_k3p, __pyx_k3, sizeof(__pyx_k3)},
  {&__pyx_k4p, __pyx_k4, sizeof(__pyx_k4)},
  {0, 0, 0}
};

static PyObject *__pyx_tp_new_8fastgeom_ThreeTuple(PyTypeObject *t, PyObject *a, PyObject *k) {
  PyObject *o = (*t->tp_alloc)(t, 0);
  return o;
}

static void __pyx_tp_dealloc_8fastgeom_ThreeTuple(PyObject *o) {
  (*o->ob_type->tp_free)(o);
}

static int __pyx_tp_traverse_8fastgeom_ThreeTuple(PyObject *o, visitproc v, void *a) {
  return 0;
}

static int __pyx_tp_clear_8fastgeom_ThreeTuple(PyObject *o) {
  return 0;
}

static struct PyMethodDef __pyx_methods_8fastgeom_ThreeTuple[] = {
  {"cross", (PyCFunction)__pyx_f_8fastgeom_10ThreeTuple_cross, METH_VARARGS|METH_KEYWORDS, 0},
  {"dot", (PyCFunction)__pyx_f_8fastgeom_10ThreeTuple_dot, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_ThreeTuple = {
  __pyx_f_8fastgeom_10ThreeTuple___add__, /*nb_add*/
  __pyx_f_8fastgeom_10ThreeTuple___sub__, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  __pyx_f_8fastgeom_10ThreeTuple___neg__, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
};

static PySequenceMethods __pyx_tp_as_sequence_ThreeTuple = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_ThreeTuple = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_ThreeTuple = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

PyTypeObject __pyx_type_8fastgeom_ThreeTuple = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "fastgeom.ThreeTuple", /*tp_name*/
  sizeof(struct __pyx_obj_8fastgeom_ThreeTuple), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_8fastgeom_ThreeTuple, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  __pyx_f_8fastgeom_10ThreeTuple___repr__, /*tp_repr*/
  &__pyx_tp_as_number_ThreeTuple, /*tp_as_number*/
  &__pyx_tp_as_sequence_ThreeTuple, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_ThreeTuple, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_ThreeTuple, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE|Py_TPFLAGS_HAVE_GC, /*tp_flags*/
  0, /*tp_doc*/
  __pyx_tp_traverse_8fastgeom_ThreeTuple, /*tp_traverse*/
  __pyx_tp_clear_8fastgeom_ThreeTuple, /*tp_clear*/
  __pyx_f_8fastgeom_10ThreeTuple___richcmp__, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_8fastgeom_ThreeTuple, /*tp_methods*/
  0, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  __pyx_f_8fastgeom_10ThreeTuple___init__, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_8fastgeom_ThreeTuple, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static PyObject *__pyx_tp_new_8fastgeom_PlueckerLine(PyTypeObject *t, PyObject *a, PyObject *k) {
  PyObject *o = (*t->tp_alloc)(t, 0);
  struct __pyx_obj_8fastgeom_PlueckerLine *p = (struct __pyx_obj_8fastgeom_PlueckerLine *)o;
  p->u = ((struct __pyx_obj_8fastgeom_ThreeTuple *)Py_None); Py_INCREF(Py_None);
  p->v = ((struct __pyx_obj_8fastgeom_ThreeTuple *)Py_None); Py_INCREF(Py_None);
  return o;
}

static void __pyx_tp_dealloc_8fastgeom_PlueckerLine(PyObject *o) {
  struct __pyx_obj_8fastgeom_PlueckerLine *p = (struct __pyx_obj_8fastgeom_PlueckerLine *)o;
  Py_XDECREF(((PyObject *)p->u));
  Py_XDECREF(((PyObject *)p->v));
  (*o->ob_type->tp_free)(o);
}

static int __pyx_tp_traverse_8fastgeom_PlueckerLine(PyObject *o, visitproc v, void *a) {
  int e;
  struct __pyx_obj_8fastgeom_PlueckerLine *p = (struct __pyx_obj_8fastgeom_PlueckerLine *)o;
  if (p->u) {
    e = (*v)(((PyObject*)p->u), a); if (e) return e;
  }
  if (p->v) {
    e = (*v)(((PyObject*)p->v), a); if (e) return e;
  }
  return 0;
}

static int __pyx_tp_clear_8fastgeom_PlueckerLine(PyObject *o) {
  struct __pyx_obj_8fastgeom_PlueckerLine *p = (struct __pyx_obj_8fastgeom_PlueckerLine *)o;
  Py_XDECREF(((PyObject *)p->u));
  p->u = ((struct __pyx_obj_8fastgeom_ThreeTuple *)Py_None); Py_INCREF(Py_None);
  Py_XDECREF(((PyObject *)p->v));
  p->v = ((struct __pyx_obj_8fastgeom_ThreeTuple *)Py_None); Py_INCREF(Py_None);
  return 0;
}

static struct PyMethodDef __pyx_methods_8fastgeom_PlueckerLine[] = {
  {"closest", (PyCFunction)__pyx_f_8fastgeom_12PlueckerLine_closest, METH_VARARGS|METH_KEYWORDS, 0},
  {"dist2", (PyCFunction)__pyx_f_8fastgeom_12PlueckerLine_dist2, METH_VARARGS|METH_KEYWORDS, 0},
  {"translate", (PyCFunction)__pyx_f_8fastgeom_12PlueckerLine_translate, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_PlueckerLine = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
};

static PySequenceMethods __pyx_tp_as_sequence_PlueckerLine = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_PlueckerLine = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_PlueckerLine = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

PyTypeObject __pyx_type_8fastgeom_PlueckerLine = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "fastgeom.PlueckerLine", /*tp_name*/
  sizeof(struct __pyx_obj_8fastgeom_PlueckerLine), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_8fastgeom_PlueckerLine, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  __pyx_f_8fastgeom_12PlueckerLine___repr__, /*tp_repr*/
  &__pyx_tp_as_number_PlueckerLine, /*tp_as_number*/
  &__pyx_tp_as_sequence_PlueckerLine, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_PlueckerLine, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_PlueckerLine, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE|Py_TPFLAGS_HAVE_GC, /*tp_flags*/
  0, /*tp_doc*/
  __pyx_tp_traverse_8fastgeom_PlueckerLine, /*tp_traverse*/
  __pyx_tp_clear_8fastgeom_PlueckerLine, /*tp_clear*/
  __pyx_f_8fastgeom_12PlueckerLine___richcmp__, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_8fastgeom_PlueckerLine, /*tp_methods*/
  0, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  __pyx_f_8fastgeom_12PlueckerLine___init__, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_8fastgeom_PlueckerLine, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static struct PyMethodDef __pyx_methods[] = {
  {"line_from_points", (PyCFunction)__pyx_f_8fastgeom_line_from_points, METH_VARARGS|METH_KEYWORDS, 0},
  {"line_from_HZline", (PyCFunction)__pyx_f_8fastgeom_line_from_HZline, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

PyMODINIT_FUNC initfastgeom(void); /*proto*/
PyMODINIT_FUNC initfastgeom(void) {
  __pyx_init_filenames();
  __pyx_m = Py_InitModule4("fastgeom", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (__Pyx_InternStrings(__pyx_intern_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (PyType_Ready(&__pyx_type_8fastgeom_ThreeTuple) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "ThreeTuple", (PyObject *)&__pyx_type_8fastgeom_ThreeTuple) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;}
  __pyx_ptype_8fastgeom_ThreeTuple = &__pyx_type_8fastgeom_ThreeTuple;
  __pyx_type_8fastgeom_PlueckerLine.tp_free = _PyObject_GC_Del;
  if (PyType_Ready(&__pyx_type_8fastgeom_PlueckerLine) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 67; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "PlueckerLine", (PyObject *)&__pyx_type_8fastgeom_PlueckerLine) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 67; goto __pyx_L1;}
  __pyx_ptype_8fastgeom_PlueckerLine = &__pyx_type_8fastgeom_PlueckerLine;

  /* "/home/astraw/src/kookaburra/flydra/src/fastgeom.pyx":116 */
  return;
  __pyx_L1:;
  __Pyx_AddTraceback("fastgeom");
}

static char *__pyx_filenames[] = {
  "fastgeom.pyx",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static int __Pyx_ArgTypeTest(PyObject *obj, PyTypeObject *type, int none_allowed, char *name) {
    if (!type) {
        PyErr_Format(PyExc_SystemError, "Missing type object");
        return 0;
    }
    if ((none_allowed && obj == Py_None) || PyObject_TypeCheck(obj, type))
        return 1;
    PyErr_Format(PyExc_TypeError,
        "Argument '%s' has incorrect type (expected %s, got %s)",
        name, type->tp_name, obj->ob_type->tp_name);
    return 0;
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

static int __Pyx_TypeTest(PyObject *obj, PyTypeObject *type) {
    if (!type) {
        PyErr_Format(PyExc_SystemError, "Missing type object");
        return 0;
    }
    if (obj == Py_None || PyObject_TypeCheck(obj, type))
        return 1;
    PyErr_Format(PyExc_TypeError, "Cannot convert %s to %s",
        obj->ob_type->tp_name, type->tp_name);
    return 0;
}

static void __Pyx_UnpackError(void) {
    PyErr_SetString(PyExc_ValueError, "unpack sequence of wrong size");
}

static PyObject *__Pyx_UnpackItem(PyObject *iter) {
    PyObject *item;
    if (!(item = PyIter_Next(iter))) {
        if (!PyErr_Occurred())
            __Pyx_UnpackError();
    }
    return item;
}

static int __Pyx_EndUnpack(PyObject *iter) {
    PyObject *item;
    if ((item = PyIter_Next(iter))) {
        Py_DECREF(item);
        __Pyx_UnpackError();
        return -1;
    }
    else if (!PyErr_Occurred())
        return 0;
    else
        return -1;
}

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb) {
    Py_XINCREF(type);
    Py_XINCREF(value);
    Py_XINCREF(tb);
    /* First, check the traceback argument, replacing None with NULL. */
    if (tb == Py_None) {
        Py_DECREF(tb);
        tb = 0;
    }
    else if (tb != NULL && !PyTraceBack_Check(tb)) {
        PyErr_SetString(PyExc_TypeError,
            "raise: arg 3 must be a traceback or None");
        goto raise_error;
    }
    /* Next, replace a missing value with None */
    if (value == NULL) {
        value = Py_None;
        Py_INCREF(value);
    }
    /* Next, repeatedly, replace a tuple exception with its first item */
    while (PyTuple_Check(type) && PyTuple_Size(type) > 0) {
        PyObject *tmp = type;
        type = PyTuple_GET_ITEM(type, 0);
        Py_INCREF(type);
        Py_DECREF(tmp);
    }
    if (PyString_Check(type)) {
        if (PyErr_Warn(PyExc_DeprecationWarning,
                "raising a string exception is deprecated"))
            goto raise_error;
    }
    else if (PyType_Check(type) || PyClass_Check(type))
        ; /*PyErr_NormalizeException(&type, &value, &tb);*/
    else {
        /* Raising an instance.  The value should be a dummy. */
        if (value != Py_None) {
            PyErr_SetString(PyExc_TypeError,
                "instance exception may not have a separate value");
            goto raise_error;
        }
        /* Normalize to raise <class>, <instance> */
        Py_DECREF(value);
        value = type;
        if (PyInstance_Check(type))
            type = (PyObject*) ((PyInstanceObject*)type)->in_class;
        else
            type = (PyObject*) type->ob_type;
        Py_INCREF(type);
    }
    PyErr_Restore(type, value, tb);
    return;
raise_error:
    Py_XDECREF(value);
    Py_XDECREF(type);
    Py_XDECREF(tb);
    return;
}

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t) {
    while (t->p) {
        *t->p = PyString_InternFromString(t->s);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_tuple = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    py_funcname = PyString_FromString(funcname);
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_tuple = PyTuple_New(0);
    if (!empty_tuple) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        empty_tuple,  /*PyObject *consts,*/
        empty_tuple,  /*PyObject *names,*/
        empty_tuple,  /*PyObject *varnames,*/
        empty_tuple,  /*PyObject *freevars,*/
        empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_tuple);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}
