/* Generated by Pyrex 0.9.6.4 on Fri May 23 19:37:50 2008 */

#define PY_SSIZE_T_CLEAN
#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#if PY_VERSION_HEX < 0x02050000
  typedef int Py_ssize_t;
  #define PY_SSIZE_T_MAX INT_MAX
  #define PY_SSIZE_T_MIN INT_MIN
  #define PyInt_FromSsize_t(z) PyInt_FromLong(z)
  #define PyInt_AsSsize_t(o)	PyInt_AsLong(o)
#endif
#ifndef WIN32
  #ifndef __stdcall
    #define __stdcall
  #endif
  #ifndef __cdecl
    #define __cdecl
  #endif
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
#include <math.h>


typedef struct {PyObject **p; char *s;} __Pyx_InternTabEntry; /*proto*/
typedef struct {PyObject **p; char *s; long n;} __Pyx_StringTabEntry; /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
static char **__pyx_f;

static int __Pyx_GetStarArgs(PyObject **args, PyObject **kwds, char *kwd_list[],     Py_ssize_t nargs, PyObject **args2, PyObject **kwds2, char rqd_kwds[]); /*proto*/

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list); /*proto*/

static PyObject *__Pyx_UnpackItem(PyObject *); /*proto*/
static int __Pyx_EndUnpack(PyObject *); /*proto*/

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t); /*proto*/

static int __Pyx_SetVtable(PyObject *dict, void *vtable); /*proto*/

static void __Pyx_AddTraceback(char *funcname); /*proto*/

/* Declarations from pmat_jacobian */

struct __pyx_obj_13pmat_jacobian_PinholeCameraModelWithJacobian {
  PyObject_HEAD
  struct __pyx_vtabstruct_13pmat_jacobian_PinholeCameraModelWithJacobian *__pyx_vtab;
  double P00;
  double P01;
  double P02;
  double P03;
  double P10;
  double P11;
  double P12;
  double P13;
  double P20;
  double P21;
  double P22;
  double P23;
  PyObject *pmat;
};


struct __pyx_vtabstruct_13pmat_jacobian_PinholeCameraModelWithJacobian {
  void (*evaluate_jacobian_at_)(struct __pyx_obj_13pmat_jacobian_PinholeCameraModelWithJacobian *,double,double,double,double,double *,double *,double *,double *,double *,double *,double *,double *);
};
static struct __pyx_vtabstruct_13pmat_jacobian_PinholeCameraModelWithJacobian *__pyx_vtabptr_13pmat_jacobian_PinholeCameraModelWithJacobian;

static PyTypeObject *__pyx_ptype_13pmat_jacobian_PinholeCameraModelWithJacobian = 0;


/* Implementation of pmat_jacobian */


static PyObject *__pyx_n_numpy;

static PyObject *__pyx_f_13pmat_jacobian_make_PinholeCameraModelWithJacobian(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_13pmat_jacobian_make_PinholeCameraModelWithJacobian(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_args = 0;
  PyObject *__pyx_v_kw = 0;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {0};
  if (__Pyx_GetStarArgs(&__pyx_args, &__pyx_kwds, __pyx_argnames, 0, &__pyx_v_args, &__pyx_v_kw, 0) < 0) return 0;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) {
    Py_XDECREF(__pyx_args);
    Py_XDECREF(__pyx_kwds);
    Py_XDECREF(__pyx_v_args);
    Py_XDECREF(__pyx_v_kw);
    return 0;
  }
  __pyx_1 = PySequence_Tuple(__pyx_v_args); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 27; goto __pyx_L1;}
  __pyx_2 = PyEval_CallObjectWithKeywords(((PyObject*)__pyx_ptype_13pmat_jacobian_PinholeCameraModelWithJacobian), __pyx_1, __pyx_v_kw); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 27; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("pmat_jacobian.make_PinholeCameraModelWithJacobian");
  __pyx_r = 0;
  __pyx_L0:;
  Py_XDECREF(__pyx_v_args);
  Py_XDECREF(__pyx_v_kw);
  Py_XDECREF(__pyx_args);
  Py_XDECREF(__pyx_kwds);
  return __pyx_r;
}

static int __pyx_f_13pmat_jacobian_30PinholeCameraModelWithJacobian___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_f_13pmat_jacobian_30PinholeCameraModelWithJacobian___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_P = 0;
  int __pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  double __pyx_4;
  static char *__pyx_argnames[] = {"P",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_P)) return -1;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_P);

  /* "/home/astraw/src/kookaburra/flydra/src/pmat_jacobian.pyx":43 */
  Py_INCREF(__pyx_v_P);
  Py_DECREF(((struct __pyx_obj_13pmat_jacobian_PinholeCameraModelWithJacobian *)__pyx_v_self)->pmat);
  ((struct __pyx_obj_13pmat_jacobian_PinholeCameraModelWithJacobian *)__pyx_v_self)->pmat = __pyx_v_P;

  /* "/home/astraw/src/kookaburra/flydra/src/pmat_jacobian.pyx":44 */
  __pyx_1 = PyInt_FromLong(0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 44; goto __pyx_L1;}
  __pyx_2 = PySlice_New(Py_None, Py_None, Py_None); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 44; goto __pyx_L1;}
  __pyx_3 = PyTuple_New(2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 44; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_1);
  PyTuple_SET_ITEM(__pyx_3, 1, __pyx_2);
  __pyx_1 = 0;
  __pyx_2 = 0;
  __pyx_1 = PyObject_GetItem(__pyx_v_P, __pyx_3); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 44; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_2 = PyObject_GetIter(__pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 44; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_3 = __Pyx_UnpackItem(__pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 44; goto __pyx_L1;}
  __pyx_4 = PyFloat_AsDouble(__pyx_3); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 44; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  ((struct __pyx_obj_13pmat_jacobian_PinholeCameraModelWithJacobian *)__pyx_v_self)->P00 = __pyx_4;
  __pyx_1 = __Pyx_UnpackItem(__pyx_2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 44; goto __pyx_L1;}
  __pyx_4 = PyFloat_AsDouble(__pyx_1); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 44; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  ((struct __pyx_obj_13pmat_jacobian_PinholeCameraModelWithJacobian *)__pyx_v_self)->P01 = __pyx_4;
  __pyx_3 = __Pyx_UnpackItem(__pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 44; goto __pyx_L1;}
  __pyx_4 = PyFloat_AsDouble(__pyx_3); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 44; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  ((struct __pyx_obj_13pmat_jacobian_PinholeCameraModelWithJacobian *)__pyx_v_self)->P02 = __pyx_4;
  __pyx_1 = __Pyx_UnpackItem(__pyx_2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 44; goto __pyx_L1;}
  __pyx_4 = PyFloat_AsDouble(__pyx_1); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 44; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  ((struct __pyx_obj_13pmat_jacobian_PinholeCameraModelWithJacobian *)__pyx_v_self)->P03 = __pyx_4;
  if (__Pyx_EndUnpack(__pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 44; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/astraw/src/kookaburra/flydra/src/pmat_jacobian.pyx":45 */
  __pyx_3 = PyInt_FromLong(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; goto __pyx_L1;}
  __pyx_1 = PySlice_New(Py_None, Py_None, Py_None); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(2); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_3);
  PyTuple_SET_ITEM(__pyx_2, 1, __pyx_1);
  __pyx_3 = 0;
  __pyx_1 = 0;
  __pyx_3 = PyObject_GetItem(__pyx_v_P, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_1 = PyObject_GetIter(__pyx_3); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_2 = __Pyx_UnpackItem(__pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; goto __pyx_L1;}
  __pyx_4 = PyFloat_AsDouble(__pyx_2); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  ((struct __pyx_obj_13pmat_jacobian_PinholeCameraModelWithJacobian *)__pyx_v_self)->P10 = __pyx_4;
  __pyx_3 = __Pyx_UnpackItem(__pyx_1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; goto __pyx_L1;}
  __pyx_4 = PyFloat_AsDouble(__pyx_3); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  ((struct __pyx_obj_13pmat_jacobian_PinholeCameraModelWithJacobian *)__pyx_v_self)->P11 = __pyx_4;
  __pyx_2 = __Pyx_UnpackItem(__pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; goto __pyx_L1;}
  __pyx_4 = PyFloat_AsDouble(__pyx_2); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  ((struct __pyx_obj_13pmat_jacobian_PinholeCameraModelWithJacobian *)__pyx_v_self)->P12 = __pyx_4;
  __pyx_3 = __Pyx_UnpackItem(__pyx_1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; goto __pyx_L1;}
  __pyx_4 = PyFloat_AsDouble(__pyx_3); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  ((struct __pyx_obj_13pmat_jacobian_PinholeCameraModelWithJacobian *)__pyx_v_self)->P13 = __pyx_4;
  if (__Pyx_EndUnpack(__pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/home/astraw/src/kookaburra/flydra/src/pmat_jacobian.pyx":46 */
  __pyx_2 = PyInt_FromLong(2); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 46; goto __pyx_L1;}
  __pyx_3 = PySlice_New(Py_None, Py_None, Py_None); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 46; goto __pyx_L1;}
  __pyx_1 = PyTuple_New(2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 46; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_1, 0, __pyx_2);
  PyTuple_SET_ITEM(__pyx_1, 1, __pyx_3);
  __pyx_2 = 0;
  __pyx_3 = 0;
  __pyx_2 = PyObject_GetItem(__pyx_v_P, __pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 46; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_3 = PyObject_GetIter(__pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 46; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_1 = __Pyx_UnpackItem(__pyx_3); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 46; goto __pyx_L1;}
  __pyx_4 = PyFloat_AsDouble(__pyx_1); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 46; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  ((struct __pyx_obj_13pmat_jacobian_PinholeCameraModelWithJacobian *)__pyx_v_self)->P20 = __pyx_4;
  __pyx_2 = __Pyx_UnpackItem(__pyx_3); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 46; goto __pyx_L1;}
  __pyx_4 = PyFloat_AsDouble(__pyx_2); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 46; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  ((struct __pyx_obj_13pmat_jacobian_PinholeCameraModelWithJacobian *)__pyx_v_self)->P21 = __pyx_4;
  __pyx_1 = __Pyx_UnpackItem(__pyx_3); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 46; goto __pyx_L1;}
  __pyx_4 = PyFloat_AsDouble(__pyx_1); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 46; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  ((struct __pyx_obj_13pmat_jacobian_PinholeCameraModelWithJacobian *)__pyx_v_self)->P22 = __pyx_4;
  __pyx_2 = __Pyx_UnpackItem(__pyx_3); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 46; goto __pyx_L1;}
  __pyx_4 = PyFloat_AsDouble(__pyx_2); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 46; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  ((struct __pyx_obj_13pmat_jacobian_PinholeCameraModelWithJacobian *)__pyx_v_self)->P23 = __pyx_4;
  if (__Pyx_EndUnpack(__pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 46; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("pmat_jacobian.PinholeCameraModelWithJacobian.__init__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_P);
  return __pyx_r;
}

static PyObject *__pyx_n_make_PinholeCameraModelWithJacobian;

static PyObject *__pyx_f_13pmat_jacobian_30PinholeCameraModelWithJacobian___reduce__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_13pmat_jacobian_30PinholeCameraModelWithJacobian___reduce__[] = "this allows PinholeCameraModelWithJacobian to be pickled";
static PyObject *__pyx_f_13pmat_jacobian_30PinholeCameraModelWithJacobian___reduce__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_args;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);
  __pyx_v_args = Py_None; Py_INCREF(Py_None);

  /* "/home/astraw/src/kookaburra/flydra/src/pmat_jacobian.pyx":50 */
  __pyx_1 = PyTuple_New(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 50; goto __pyx_L1;}
  Py_INCREF(((struct __pyx_obj_13pmat_jacobian_PinholeCameraModelWithJacobian *)__pyx_v_self)->pmat);
  PyTuple_SET_ITEM(__pyx_1, 0, ((struct __pyx_obj_13pmat_jacobian_PinholeCameraModelWithJacobian *)__pyx_v_self)->pmat);
  Py_DECREF(__pyx_v_args);
  __pyx_v_args = __pyx_1;
  __pyx_1 = 0;

  /* "/home/astraw/src/kookaburra/flydra/src/pmat_jacobian.pyx":51 */
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_make_PinholeCameraModelWithJacobian); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 51; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(2); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 51; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_1);
  Py_INCREF(__pyx_v_args);
  PyTuple_SET_ITEM(__pyx_2, 1, __pyx_v_args);
  __pyx_1 = 0;
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("pmat_jacobian.PinholeCameraModelWithJacobian.__reduce__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_args);
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static void __pyx_f_13pmat_jacobian_30PinholeCameraModelWithJacobian_evaluate_jacobian_at_(struct __pyx_obj_13pmat_jacobian_PinholeCameraModelWithJacobian *__pyx_v_self,double __pyx_v_x,double __pyx_v_y,double __pyx_v_z,double __pyx_v_w,double *__pyx_v_ux,double *__pyx_v_uy,double *__pyx_v_uz,double *__pyx_v_uw,double *__pyx_v_vx,double *__pyx_v_vy,double *__pyx_v_vz,double *__pyx_v_vw) {
  Py_INCREF(__pyx_v_self);

  /* "/home/astraw/src/kookaburra/flydra/src/pmat_jacobian.pyx":59 */
  (__pyx_v_ux[0]) = ((((-__pyx_v_self->P20) * pow(((((__pyx_v_self->P20 * __pyx_v_x) + (__pyx_v_self->P21 * __pyx_v_y)) + (__pyx_v_self->P22 * __pyx_v_z)) + (__pyx_v_self->P23 * __pyx_v_w)), (-2))) * ((((__pyx_v_self->P00 * __pyx_v_x) + (__pyx_v_self->P01 * __pyx_v_y)) + (__pyx_v_self->P02 * __pyx_v_z)) + (__pyx_v_self->P03 * __pyx_v_w))) + (__pyx_v_self->P00 / ((((__pyx_v_self->P20 * __pyx_v_x) + (__pyx_v_self->P21 * __pyx_v_y)) + (__pyx_v_self->P22 * __pyx_v_z)) + (__pyx_v_self->P23 * __pyx_v_w))));

  /* "/home/astraw/src/kookaburra/flydra/src/pmat_jacobian.pyx":61 */
  (__pyx_v_uy[0]) = ((((-__pyx_v_self->P21) * pow(((((__pyx_v_self->P20 * __pyx_v_x) + (__pyx_v_self->P21 * __pyx_v_y)) + (__pyx_v_self->P22 * __pyx_v_z)) + (__pyx_v_self->P23 * __pyx_v_w)), (-2))) * ((((__pyx_v_self->P00 * __pyx_v_x) + (__pyx_v_self->P01 * __pyx_v_y)) + (__pyx_v_self->P02 * __pyx_v_z)) + (__pyx_v_self->P03 * __pyx_v_w))) + (__pyx_v_self->P01 / ((((__pyx_v_self->P20 * __pyx_v_x) + (__pyx_v_self->P21 * __pyx_v_y)) + (__pyx_v_self->P22 * __pyx_v_z)) + (__pyx_v_self->P23 * __pyx_v_w))));

  /* "/home/astraw/src/kookaburra/flydra/src/pmat_jacobian.pyx":63 */
  (__pyx_v_uz[0]) = ((((-__pyx_v_self->P22) * pow(((((__pyx_v_self->P20 * __pyx_v_x) + (__pyx_v_self->P21 * __pyx_v_y)) + (__pyx_v_self->P22 * __pyx_v_z)) + (__pyx_v_self->P23 * __pyx_v_w)), (-2))) * ((((__pyx_v_self->P00 * __pyx_v_x) + (__pyx_v_self->P01 * __pyx_v_y)) + (__pyx_v_self->P02 * __pyx_v_z)) + (__pyx_v_self->P03 * __pyx_v_w))) + (__pyx_v_self->P02 / ((((__pyx_v_self->P20 * __pyx_v_x) + (__pyx_v_self->P21 * __pyx_v_y)) + (__pyx_v_self->P22 * __pyx_v_z)) + (__pyx_v_self->P23 * __pyx_v_w))));

  /* "/home/astraw/src/kookaburra/flydra/src/pmat_jacobian.pyx":65 */
  (__pyx_v_uw[0]) = ((((-__pyx_v_self->P23) * pow(((((__pyx_v_self->P20 * __pyx_v_x) + (__pyx_v_self->P21 * __pyx_v_y)) + (__pyx_v_self->P22 * __pyx_v_z)) + (__pyx_v_self->P23 * __pyx_v_w)), (-2))) * ((((__pyx_v_self->P00 * __pyx_v_x) + (__pyx_v_self->P01 * __pyx_v_y)) + (__pyx_v_self->P02 * __pyx_v_z)) + (__pyx_v_self->P03 * __pyx_v_w))) + (__pyx_v_self->P03 / ((((__pyx_v_self->P20 * __pyx_v_x) + (__pyx_v_self->P21 * __pyx_v_y)) + (__pyx_v_self->P22 * __pyx_v_z)) + (__pyx_v_self->P23 * __pyx_v_w))));

  /* "/home/astraw/src/kookaburra/flydra/src/pmat_jacobian.pyx":68 */
  (__pyx_v_vx[0]) = ((((-__pyx_v_self->P20) * pow(((((__pyx_v_self->P20 * __pyx_v_x) + (__pyx_v_self->P21 * __pyx_v_y)) + (__pyx_v_self->P22 * __pyx_v_z)) + (__pyx_v_self->P23 * __pyx_v_w)), (-2))) * ((((__pyx_v_self->P10 * __pyx_v_x) + (__pyx_v_self->P11 * __pyx_v_y)) + (__pyx_v_self->P12 * __pyx_v_z)) + (__pyx_v_self->P13 * __pyx_v_w))) + (__pyx_v_self->P10 / ((((__pyx_v_self->P20 * __pyx_v_x) + (__pyx_v_self->P21 * __pyx_v_y)) + (__pyx_v_self->P22 * __pyx_v_z)) + (__pyx_v_self->P23 * __pyx_v_w))));

  /* "/home/astraw/src/kookaburra/flydra/src/pmat_jacobian.pyx":70 */
  (__pyx_v_vy[0]) = ((((-__pyx_v_self->P21) * pow(((((__pyx_v_self->P20 * __pyx_v_x) + (__pyx_v_self->P21 * __pyx_v_y)) + (__pyx_v_self->P22 * __pyx_v_z)) + (__pyx_v_self->P23 * __pyx_v_w)), (-2))) * ((((__pyx_v_self->P10 * __pyx_v_x) + (__pyx_v_self->P11 * __pyx_v_y)) + (__pyx_v_self->P12 * __pyx_v_z)) + (__pyx_v_self->P13 * __pyx_v_w))) + (__pyx_v_self->P11 / ((((__pyx_v_self->P20 * __pyx_v_x) + (__pyx_v_self->P21 * __pyx_v_y)) + (__pyx_v_self->P22 * __pyx_v_z)) + (__pyx_v_self->P23 * __pyx_v_w))));

  /* "/home/astraw/src/kookaburra/flydra/src/pmat_jacobian.pyx":72 */
  (__pyx_v_vz[0]) = ((((-__pyx_v_self->P22) * pow(((((__pyx_v_self->P20 * __pyx_v_x) + (__pyx_v_self->P21 * __pyx_v_y)) + (__pyx_v_self->P22 * __pyx_v_z)) + (__pyx_v_self->P23 * __pyx_v_w)), (-2))) * ((((__pyx_v_self->P10 * __pyx_v_x) + (__pyx_v_self->P11 * __pyx_v_y)) + (__pyx_v_self->P12 * __pyx_v_z)) + (__pyx_v_self->P13 * __pyx_v_w))) + (__pyx_v_self->P12 / ((((__pyx_v_self->P20 * __pyx_v_x) + (__pyx_v_self->P21 * __pyx_v_y)) + (__pyx_v_self->P22 * __pyx_v_z)) + (__pyx_v_self->P23 * __pyx_v_w))));

  /* "/home/astraw/src/kookaburra/flydra/src/pmat_jacobian.pyx":74 */
  (__pyx_v_vw[0]) = ((((-__pyx_v_self->P23) * pow(((((__pyx_v_self->P20 * __pyx_v_x) + (__pyx_v_self->P21 * __pyx_v_y)) + (__pyx_v_self->P22 * __pyx_v_z)) + (__pyx_v_self->P23 * __pyx_v_w)), (-2))) * ((((__pyx_v_self->P10 * __pyx_v_x) + (__pyx_v_self->P11 * __pyx_v_y)) + (__pyx_v_self->P12 * __pyx_v_z)) + (__pyx_v_self->P13 * __pyx_v_w))) + (__pyx_v_self->P13 / ((((__pyx_v_self->P20 * __pyx_v_x) + (__pyx_v_self->P21 * __pyx_v_y)) + (__pyx_v_self->P22 * __pyx_v_z)) + (__pyx_v_self->P23 * __pyx_v_w))));

  Py_DECREF(__pyx_v_self);
}

static PyObject *__pyx_n_array;
static PyObject *__pyx_n_float64;
static PyObject *__pyx_n_dtype;


static PyObject *__pyx_f_13pmat_jacobian_30PinholeCameraModelWithJacobian_evaluate_jacobian_from_homogeneous(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_13pmat_jacobian_30PinholeCameraModelWithJacobian_evaluate_jacobian_from_homogeneous(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_X = 0;
  double __pyx_v_ux;
  double __pyx_v_uy;
  double __pyx_v_uz;
  double __pyx_v_uw;
  double __pyx_v_vx;
  double __pyx_v_vy;
  double __pyx_v_vz;
  double __pyx_v_vw;
  double __pyx_v_w;
  PyObject *__pyx_v_x;
  PyObject *__pyx_v_y;
  PyObject *__pyx_v_z;
  PyObject *__pyx_v_J;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  double __pyx_3;
  double __pyx_4;
  double __pyx_5;
  PyObject *__pyx_6 = 0;
  PyObject *__pyx_7 = 0;
  PyObject *__pyx_8 = 0;
  PyObject *__pyx_9 = 0;
  PyObject *__pyx_10 = 0;
  static char *__pyx_argnames[] = {"X",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_X)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_X);
  __pyx_v_x = Py_None; Py_INCREF(Py_None);
  __pyx_v_y = Py_None; Py_INCREF(Py_None);
  __pyx_v_z = Py_None; Py_INCREF(Py_None);
  __pyx_v_J = Py_None; Py_INCREF(Py_None);

  /* "/home/astraw/src/kookaburra/flydra/src/pmat_jacobian.pyx":81 */
  __pyx_1 = PyObject_GetIter(__pyx_v_X); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 81; goto __pyx_L1;}
  __pyx_2 = __Pyx_UnpackItem(__pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 81; goto __pyx_L1;}
  Py_DECREF(__pyx_v_x);
  __pyx_v_x = __pyx_2;
  __pyx_2 = 0;
  __pyx_2 = __Pyx_UnpackItem(__pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 81; goto __pyx_L1;}
  Py_DECREF(__pyx_v_y);
  __pyx_v_y = __pyx_2;
  __pyx_2 = 0;
  __pyx_2 = __Pyx_UnpackItem(__pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 81; goto __pyx_L1;}
  Py_DECREF(__pyx_v_z);
  __pyx_v_z = __pyx_2;
  __pyx_2 = 0;
  __pyx_2 = __Pyx_UnpackItem(__pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 81; goto __pyx_L1;}
  __pyx_3 = PyFloat_AsDouble(__pyx_2); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 81; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_v_w = __pyx_3;
  if (__Pyx_EndUnpack(__pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 81; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/home/astraw/src/kookaburra/flydra/src/pmat_jacobian.pyx":82 */
  __pyx_3 = PyFloat_AsDouble(__pyx_v_x); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 82; goto __pyx_L1;}
  __pyx_4 = PyFloat_AsDouble(__pyx_v_y); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 82; goto __pyx_L1;}
  __pyx_5 = PyFloat_AsDouble(__pyx_v_z); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 82; goto __pyx_L1;}
  ((struct __pyx_vtabstruct_13pmat_jacobian_PinholeCameraModelWithJacobian *)((struct __pyx_obj_13pmat_jacobian_PinholeCameraModelWithJacobian *)__pyx_v_self)->__pyx_vtab)->evaluate_jacobian_at_(((struct __pyx_obj_13pmat_jacobian_PinholeCameraModelWithJacobian *)__pyx_v_self),__pyx_3,__pyx_4,__pyx_5,__pyx_v_w,(&__pyx_v_ux),(&__pyx_v_uy),(&__pyx_v_uz),(&__pyx_v_uw),(&__pyx_v_vx),(&__pyx_v_vy),(&__pyx_v_vz),(&__pyx_v_vw));

  /* "/home/astraw/src/kookaburra/flydra/src/pmat_jacobian.pyx":84 */
  __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_numpy); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 84; goto __pyx_L1;}
  __pyx_1 = PyObject_GetAttr(__pyx_2, __pyx_n_array); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 84; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_2 = PyFloat_FromDouble(__pyx_v_ux); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 84; goto __pyx_L1;}
  __pyx_6 = PyFloat_FromDouble(__pyx_v_uy); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 84; goto __pyx_L1;}
  __pyx_7 = PyFloat_FromDouble(__pyx_v_uz); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 84; goto __pyx_L1;}
  __pyx_8 = PyFloat_FromDouble(__pyx_v_uw); if (!__pyx_8) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 84; goto __pyx_L1;}
  __pyx_9 = PyList_New(4); if (!__pyx_9) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 84; goto __pyx_L1;}
  PyList_SET_ITEM(__pyx_9, 0, __pyx_2);
  PyList_SET_ITEM(__pyx_9, 1, __pyx_6);
  PyList_SET_ITEM(__pyx_9, 2, __pyx_7);
  PyList_SET_ITEM(__pyx_9, 3, __pyx_8);
  __pyx_2 = 0;
  __pyx_6 = 0;
  __pyx_7 = 0;
  __pyx_8 = 0;
  __pyx_2 = PyFloat_FromDouble(__pyx_v_vx); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 85; goto __pyx_L1;}
  __pyx_6 = PyFloat_FromDouble(__pyx_v_vy); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 85; goto __pyx_L1;}
  __pyx_7 = PyFloat_FromDouble(__pyx_v_vz); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 85; goto __pyx_L1;}
  __pyx_8 = PyFloat_FromDouble(__pyx_v_vw); if (!__pyx_8) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 85; goto __pyx_L1;}
  __pyx_10 = PyList_New(4); if (!__pyx_10) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 85; goto __pyx_L1;}
  PyList_SET_ITEM(__pyx_10, 0, __pyx_2);
  PyList_SET_ITEM(__pyx_10, 1, __pyx_6);
  PyList_SET_ITEM(__pyx_10, 2, __pyx_7);
  PyList_SET_ITEM(__pyx_10, 3, __pyx_8);
  __pyx_2 = 0;
  __pyx_6 = 0;
  __pyx_7 = 0;
  __pyx_8 = 0;
  __pyx_2 = PyList_New(2); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 84; goto __pyx_L1;}
  PyList_SET_ITEM(__pyx_2, 0, __pyx_9);
  PyList_SET_ITEM(__pyx_2, 1, __pyx_10);
  __pyx_9 = 0;
  __pyx_10 = 0;
  __pyx_6 = PyTuple_New(1); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 84; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_6, 0, __pyx_2);
  __pyx_2 = 0;
  __pyx_7 = PyDict_New(); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 84; goto __pyx_L1;}
  __pyx_8 = __Pyx_GetName(__pyx_m, __pyx_n_numpy); if (!__pyx_8) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 86; goto __pyx_L1;}
  __pyx_9 = PyObject_GetAttr(__pyx_8, __pyx_n_float64); if (!__pyx_9) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 86; goto __pyx_L1;}
  Py_DECREF(__pyx_8); __pyx_8 = 0;
  if (PyDict_SetItem(__pyx_7, __pyx_n_dtype, __pyx_9) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 84; goto __pyx_L1;}
  Py_DECREF(__pyx_9); __pyx_9 = 0;
  __pyx_10 = PyEval_CallObjectWithKeywords(__pyx_1, __pyx_6, __pyx_7); if (!__pyx_10) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 84; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_6); __pyx_6 = 0;
  Py_DECREF(__pyx_7); __pyx_7 = 0;
  Py_DECREF(__pyx_v_J);
  __pyx_v_J = __pyx_10;
  __pyx_10 = 0;

  /* "/home/astraw/src/kookaburra/flydra/src/pmat_jacobian.pyx":87 */
  Py_INCREF(__pyx_v_J);
  __pyx_r = __pyx_v_J;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_6);
  Py_XDECREF(__pyx_7);
  Py_XDECREF(__pyx_8);
  Py_XDECREF(__pyx_9);
  Py_XDECREF(__pyx_10);
  __Pyx_AddTraceback("pmat_jacobian.PinholeCameraModelWithJacobian.evaluate_jacobian_from_homogeneous");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_x);
  Py_DECREF(__pyx_v_y);
  Py_DECREF(__pyx_v_z);
  Py_DECREF(__pyx_v_J);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_X);
  return __pyx_r;
}


static PyObject *__pyx_f_13pmat_jacobian_30PinholeCameraModelWithJacobian_evaluate_jacobian_at(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_13pmat_jacobian_30PinholeCameraModelWithJacobian_evaluate_jacobian_at(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_X = 0;
  double __pyx_v_ux;
  double __pyx_v_uy;
  double __pyx_v_uz;
  double __pyx_v_uw;
  double __pyx_v_vx;
  double __pyx_v_vy;
  double __pyx_v_vz;
  double __pyx_v_vw;
  double __pyx_v_w;
  PyObject *__pyx_v_x;
  PyObject *__pyx_v_y;
  PyObject *__pyx_v_z;
  PyObject *__pyx_v_J;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  double __pyx_3;
  double __pyx_4;
  double __pyx_5;
  PyObject *__pyx_6 = 0;
  PyObject *__pyx_7 = 0;
  PyObject *__pyx_8 = 0;
  PyObject *__pyx_9 = 0;
  static char *__pyx_argnames[] = {"X",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_X)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_X);
  __pyx_v_x = Py_None; Py_INCREF(Py_None);
  __pyx_v_y = Py_None; Py_INCREF(Py_None);
  __pyx_v_z = Py_None; Py_INCREF(Py_None);
  __pyx_v_J = Py_None; Py_INCREF(Py_None);

  /* "/home/astraw/src/kookaburra/flydra/src/pmat_jacobian.pyx":93 */
  __pyx_1 = PySequence_GetSlice(__pyx_v_X, 0, 3); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 93; goto __pyx_L1;}
  __pyx_2 = PyObject_GetIter(__pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 93; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = __Pyx_UnpackItem(__pyx_2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 93; goto __pyx_L1;}
  Py_DECREF(__pyx_v_x);
  __pyx_v_x = __pyx_1;
  __pyx_1 = 0;
  __pyx_1 = __Pyx_UnpackItem(__pyx_2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 93; goto __pyx_L1;}
  Py_DECREF(__pyx_v_y);
  __pyx_v_y = __pyx_1;
  __pyx_1 = 0;
  __pyx_1 = __Pyx_UnpackItem(__pyx_2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 93; goto __pyx_L1;}
  Py_DECREF(__pyx_v_z);
  __pyx_v_z = __pyx_1;
  __pyx_1 = 0;
  if (__Pyx_EndUnpack(__pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 93; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/astraw/src/kookaburra/flydra/src/pmat_jacobian.pyx":94 */
  __pyx_v_w = 1.0;

  /* "/home/astraw/src/kookaburra/flydra/src/pmat_jacobian.pyx":95 */
  __pyx_3 = PyFloat_AsDouble(__pyx_v_x); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; goto __pyx_L1;}
  __pyx_4 = PyFloat_AsDouble(__pyx_v_y); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; goto __pyx_L1;}
  __pyx_5 = PyFloat_AsDouble(__pyx_v_z); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; goto __pyx_L1;}
  ((struct __pyx_vtabstruct_13pmat_jacobian_PinholeCameraModelWithJacobian *)((struct __pyx_obj_13pmat_jacobian_PinholeCameraModelWithJacobian *)__pyx_v_self)->__pyx_vtab)->evaluate_jacobian_at_(((struct __pyx_obj_13pmat_jacobian_PinholeCameraModelWithJacobian *)__pyx_v_self),__pyx_3,__pyx_4,__pyx_5,__pyx_v_w,(&__pyx_v_ux),(&__pyx_v_uy),(&__pyx_v_uz),(&__pyx_v_uw),(&__pyx_v_vx),(&__pyx_v_vy),(&__pyx_v_vz),(&__pyx_v_vw));

  /* "/home/astraw/src/kookaburra/flydra/src/pmat_jacobian.pyx":97 */
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_numpy); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 97; goto __pyx_L1;}
  __pyx_2 = PyObject_GetAttr(__pyx_1, __pyx_n_array); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 97; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyFloat_FromDouble(__pyx_v_ux); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 97; goto __pyx_L1;}
  __pyx_6 = PyFloat_FromDouble(__pyx_v_uy); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 97; goto __pyx_L1;}
  __pyx_7 = PyFloat_FromDouble(__pyx_v_uz); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 97; goto __pyx_L1;}
  __pyx_8 = PyList_New(3); if (!__pyx_8) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 97; goto __pyx_L1;}
  PyList_SET_ITEM(__pyx_8, 0, __pyx_1);
  PyList_SET_ITEM(__pyx_8, 1, __pyx_6);
  PyList_SET_ITEM(__pyx_8, 2, __pyx_7);
  __pyx_1 = 0;
  __pyx_6 = 0;
  __pyx_7 = 0;
  __pyx_1 = PyFloat_FromDouble(__pyx_v_vx); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 98; goto __pyx_L1;}
  __pyx_6 = PyFloat_FromDouble(__pyx_v_vy); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 98; goto __pyx_L1;}
  __pyx_7 = PyFloat_FromDouble(__pyx_v_vz); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 98; goto __pyx_L1;}
  __pyx_9 = PyList_New(3); if (!__pyx_9) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 98; goto __pyx_L1;}
  PyList_SET_ITEM(__pyx_9, 0, __pyx_1);
  PyList_SET_ITEM(__pyx_9, 1, __pyx_6);
  PyList_SET_ITEM(__pyx_9, 2, __pyx_7);
  __pyx_1 = 0;
  __pyx_6 = 0;
  __pyx_7 = 0;
  __pyx_1 = PyList_New(2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 97; goto __pyx_L1;}
  PyList_SET_ITEM(__pyx_1, 0, __pyx_8);
  PyList_SET_ITEM(__pyx_1, 1, __pyx_9);
  __pyx_8 = 0;
  __pyx_9 = 0;
  __pyx_6 = PyTuple_New(1); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 97; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_6, 0, __pyx_1);
  __pyx_1 = 0;
  __pyx_7 = PyDict_New(); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 97; goto __pyx_L1;}
  __pyx_8 = __Pyx_GetName(__pyx_m, __pyx_n_numpy); if (!__pyx_8) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 99; goto __pyx_L1;}
  __pyx_9 = PyObject_GetAttr(__pyx_8, __pyx_n_float64); if (!__pyx_9) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 99; goto __pyx_L1;}
  Py_DECREF(__pyx_8); __pyx_8 = 0;
  if (PyDict_SetItem(__pyx_7, __pyx_n_dtype, __pyx_9) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 97; goto __pyx_L1;}
  Py_DECREF(__pyx_9); __pyx_9 = 0;
  __pyx_1 = PyEval_CallObjectWithKeywords(__pyx_2, __pyx_6, __pyx_7); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 97; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_6); __pyx_6 = 0;
  Py_DECREF(__pyx_7); __pyx_7 = 0;
  Py_DECREF(__pyx_v_J);
  __pyx_v_J = __pyx_1;
  __pyx_1 = 0;

  /* "/home/astraw/src/kookaburra/flydra/src/pmat_jacobian.pyx":100 */
  Py_INCREF(__pyx_v_J);
  __pyx_r = __pyx_v_J;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_6);
  Py_XDECREF(__pyx_7);
  Py_XDECREF(__pyx_8);
  Py_XDECREF(__pyx_9);
  __Pyx_AddTraceback("pmat_jacobian.PinholeCameraModelWithJacobian.evaluate_jacobian_at");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_x);
  Py_DECREF(__pyx_v_y);
  Py_DECREF(__pyx_v_z);
  Py_DECREF(__pyx_v_J);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_X);
  return __pyx_r;
}

static PyObject *__pyx_n_ones;
static PyObject *__pyx_n_dot;

static PyObject *__pyx_f_13pmat_jacobian_30PinholeCameraModelWithJacobian___call__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_13pmat_jacobian_30PinholeCameraModelWithJacobian___call__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_X = 0;
  PyObject *__pyx_v_predicted3d_homogeneous;
  PyObject *__pyx_v_uvw;
  PyObject *__pyx_v_Y;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  static char *__pyx_argnames[] = {"X",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_X)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_X);
  __pyx_v_predicted3d_homogeneous = Py_None; Py_INCREF(Py_None);
  __pyx_v_uvw = Py_None; Py_INCREF(Py_None);
  __pyx_v_Y = Py_None; Py_INCREF(Py_None);

  /* "/home/astraw/src/kookaburra/flydra/src/pmat_jacobian.pyx":106 */
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_numpy); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 106; goto __pyx_L1;}
  __pyx_2 = PyObject_GetAttr(__pyx_1, __pyx_n_ones); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 106; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyInt_FromLong(4); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 106; goto __pyx_L1;}
  __pyx_3 = PyInt_FromLong(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 106; goto __pyx_L1;}
  __pyx_4 = PyTuple_New(2); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 106; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_1);
  PyTuple_SET_ITEM(__pyx_4, 1, __pyx_3);
  __pyx_1 = 0;
  __pyx_3 = 0;
  __pyx_1 = PyTuple_New(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 106; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_1, 0, __pyx_4);
  __pyx_4 = 0;
  __pyx_3 = PyObject_CallObject(__pyx_2, __pyx_1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 106; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_v_predicted3d_homogeneous);
  __pyx_v_predicted3d_homogeneous = __pyx_3;
  __pyx_3 = 0;

  /* "/home/astraw/src/kookaburra/flydra/src/pmat_jacobian.pyx":107 */
  __pyx_4 = PySequence_GetSlice(__pyx_v_X, 0, 3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 107; goto __pyx_L1;}
  __pyx_2 = PyInt_FromLong(3); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 107; goto __pyx_L1;}
  __pyx_1 = PySlice_New(Py_None, __pyx_2, Py_None); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 107; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_3 = PyInt_FromLong(0); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 107; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(2); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 107; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_1);
  PyTuple_SET_ITEM(__pyx_2, 1, __pyx_3);
  __pyx_1 = 0;
  __pyx_3 = 0;
  if (PyObject_SetItem(__pyx_v_predicted3d_homogeneous, __pyx_2, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 107; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_4); __pyx_4 = 0;

  /* "/home/astraw/src/kookaburra/flydra/src/pmat_jacobian.pyx":108 */
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_numpy); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 108; goto __pyx_L1;}
  __pyx_3 = PyObject_GetAttr(__pyx_1, __pyx_n_dot); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 108; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_4 = PyTuple_New(2); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 108; goto __pyx_L1;}
  Py_INCREF(((struct __pyx_obj_13pmat_jacobian_PinholeCameraModelWithJacobian *)__pyx_v_self)->pmat);
  PyTuple_SET_ITEM(__pyx_4, 0, ((struct __pyx_obj_13pmat_jacobian_PinholeCameraModelWithJacobian *)__pyx_v_self)->pmat);
  Py_INCREF(__pyx_v_predicted3d_homogeneous);
  PyTuple_SET_ITEM(__pyx_4, 1, __pyx_v_predicted3d_homogeneous);
  __pyx_2 = PyObject_CallObject(__pyx_3, __pyx_4); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 108; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  Py_DECREF(__pyx_v_uvw);
  __pyx_v_uvw = __pyx_2;
  __pyx_2 = 0;

  /* "/home/astraw/src/kookaburra/flydra/src/pmat_jacobian.pyx":109 */
  __pyx_1 = PyInt_FromLong(2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 109; goto __pyx_L1;}
  __pyx_3 = PyObject_GetItem(__pyx_v_uvw, __pyx_1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 109; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_4 = PyNumber_Divide(__pyx_v_uvw, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 109; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_2 = PyInt_FromLong(2); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 109; goto __pyx_L1;}
  __pyx_1 = PySlice_New(Py_None, __pyx_2, Py_None); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 109; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_3 = PyInt_FromLong(0); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 109; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(2); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 109; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_1);
  PyTuple_SET_ITEM(__pyx_2, 1, __pyx_3);
  __pyx_1 = 0;
  __pyx_3 = 0;
  __pyx_1 = PyObject_GetItem(__pyx_4, __pyx_2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 109; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_v_Y);
  __pyx_v_Y = __pyx_1;
  __pyx_1 = 0;

  /* "/home/astraw/src/kookaburra/flydra/src/pmat_jacobian.pyx":110 */
  Py_INCREF(__pyx_v_Y);
  __pyx_r = __pyx_v_Y;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("pmat_jacobian.PinholeCameraModelWithJacobian.__call__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_predicted3d_homogeneous);
  Py_DECREF(__pyx_v_uvw);
  Py_DECREF(__pyx_v_Y);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_X);
  return __pyx_r;
}

static __Pyx_InternTabEntry __pyx_intern_tab[] = {
  {&__pyx_n_array, "array"},
  {&__pyx_n_dot, "dot"},
  {&__pyx_n_dtype, "dtype"},
  {&__pyx_n_float64, "float64"},
  {&__pyx_n_make_PinholeCameraModelWithJacobian, "make_PinholeCameraModelWithJacobian"},
  {&__pyx_n_numpy, "numpy"},
  {&__pyx_n_ones, "ones"},
  {0, 0}
};
static struct __pyx_vtabstruct_13pmat_jacobian_PinholeCameraModelWithJacobian __pyx_vtable_13pmat_jacobian_PinholeCameraModelWithJacobian;

static PyObject *__pyx_tp_new_13pmat_jacobian_PinholeCameraModelWithJacobian(PyTypeObject *t, PyObject *a, PyObject *k) {
  struct __pyx_obj_13pmat_jacobian_PinholeCameraModelWithJacobian *p;
  PyObject *o = (*t->tp_alloc)(t, 0);
  if (!o) return 0;
  p = ((struct __pyx_obj_13pmat_jacobian_PinholeCameraModelWithJacobian *)o);
  *(struct __pyx_vtabstruct_13pmat_jacobian_PinholeCameraModelWithJacobian **)&p->__pyx_vtab = __pyx_vtabptr_13pmat_jacobian_PinholeCameraModelWithJacobian;
  p->pmat = Py_None; Py_INCREF(Py_None);
  return o;
}

static void __pyx_tp_dealloc_13pmat_jacobian_PinholeCameraModelWithJacobian(PyObject *o) {
  struct __pyx_obj_13pmat_jacobian_PinholeCameraModelWithJacobian *p = (struct __pyx_obj_13pmat_jacobian_PinholeCameraModelWithJacobian *)o;
  Py_XDECREF(p->pmat);
  (*o->ob_type->tp_free)(o);
}

static int __pyx_tp_traverse_13pmat_jacobian_PinholeCameraModelWithJacobian(PyObject *o, visitproc v, void *a) {
  int e;
  struct __pyx_obj_13pmat_jacobian_PinholeCameraModelWithJacobian *p = (struct __pyx_obj_13pmat_jacobian_PinholeCameraModelWithJacobian *)o;
  if (p->pmat) {
    e = (*v)(p->pmat, a); if (e) return e;
  }
  return 0;
}

static int __pyx_tp_clear_13pmat_jacobian_PinholeCameraModelWithJacobian(PyObject *o) {
  struct __pyx_obj_13pmat_jacobian_PinholeCameraModelWithJacobian *p = (struct __pyx_obj_13pmat_jacobian_PinholeCameraModelWithJacobian *)o;
  Py_XDECREF(p->pmat);
  p->pmat = Py_None; Py_INCREF(Py_None);
  return 0;
}

static struct PyMethodDef __pyx_methods_13pmat_jacobian_PinholeCameraModelWithJacobian[] = {
  {"__reduce__", (PyCFunction)__pyx_f_13pmat_jacobian_30PinholeCameraModelWithJacobian___reduce__, METH_VARARGS|METH_KEYWORDS, __pyx_doc_13pmat_jacobian_30PinholeCameraModelWithJacobian___reduce__},
  {"evaluate_jacobian_from_homogeneous", (PyCFunction)__pyx_f_13pmat_jacobian_30PinholeCameraModelWithJacobian_evaluate_jacobian_from_homogeneous, METH_VARARGS|METH_KEYWORDS, 0},
  {"evaluate_jacobian_at", (PyCFunction)__pyx_f_13pmat_jacobian_30PinholeCameraModelWithJacobian_evaluate_jacobian_at, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_PinholeCameraModelWithJacobian = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
  #if Py_TPFLAGS_DEFAULT & Py_TPFLAGS_HAVE_INDEX
  0, /*nb_index*/
  #endif
};

static PySequenceMethods __pyx_tp_as_sequence_PinholeCameraModelWithJacobian = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_PinholeCameraModelWithJacobian = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_PinholeCameraModelWithJacobian = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

PyTypeObject __pyx_type_13pmat_jacobian_PinholeCameraModelWithJacobian = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "pmat_jacobian.PinholeCameraModelWithJacobian", /*tp_name*/
  sizeof(struct __pyx_obj_13pmat_jacobian_PinholeCameraModelWithJacobian), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_13pmat_jacobian_PinholeCameraModelWithJacobian, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_PinholeCameraModelWithJacobian, /*tp_as_number*/
  &__pyx_tp_as_sequence_PinholeCameraModelWithJacobian, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_PinholeCameraModelWithJacobian, /*tp_as_mapping*/
  0, /*tp_hash*/
  __pyx_f_13pmat_jacobian_30PinholeCameraModelWithJacobian___call__, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_PinholeCameraModelWithJacobian, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE|Py_TPFLAGS_HAVE_GC, /*tp_flags*/
  "Represent the 3D projection of a camera.\n\n    Camera projection is a non-linear process where the 3D coordinate\n    X = (x,y,z) is transformed to the 2D coordinate Y = (r,s) on the\n    image plane by the function h:\n\n                          Y = h(X)\n\n    This class implements this function and allows one to evaluate the\n    jacobian at various X, as well.\n\n    ", /*tp_doc*/
  __pyx_tp_traverse_13pmat_jacobian_PinholeCameraModelWithJacobian, /*tp_traverse*/
  __pyx_tp_clear_13pmat_jacobian_PinholeCameraModelWithJacobian, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_13pmat_jacobian_PinholeCameraModelWithJacobian, /*tp_methods*/
  0, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  __pyx_f_13pmat_jacobian_30PinholeCameraModelWithJacobian___init__, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_13pmat_jacobian_PinholeCameraModelWithJacobian, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static struct PyMethodDef __pyx_methods[] = {
  {"make_PinholeCameraModelWithJacobian", (PyCFunction)__pyx_f_13pmat_jacobian_make_PinholeCameraModelWithJacobian, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

PyMODINIT_FUNC initpmat_jacobian(void); /*proto*/
PyMODINIT_FUNC initpmat_jacobian(void) {
  PyObject *__pyx_1 = 0;
  __pyx_init_filenames();
  __pyx_m = Py_InitModule4("pmat_jacobian", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; goto __pyx_L1;};
  Py_INCREF(__pyx_m);
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; goto __pyx_L1;};
  if (__Pyx_InternStrings(__pyx_intern_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; goto __pyx_L1;};
  __pyx_vtabptr_13pmat_jacobian_PinholeCameraModelWithJacobian = &__pyx_vtable_13pmat_jacobian_PinholeCameraModelWithJacobian;
  *(void(**)(void))&__pyx_vtable_13pmat_jacobian_PinholeCameraModelWithJacobian.evaluate_jacobian_at_ = (void(*)(void))__pyx_f_13pmat_jacobian_30PinholeCameraModelWithJacobian_evaluate_jacobian_at_;
  __pyx_type_13pmat_jacobian_PinholeCameraModelWithJacobian.tp_free = _PyObject_GC_Del;
  if (PyType_Ready(&__pyx_type_13pmat_jacobian_PinholeCameraModelWithJacobian) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 29; goto __pyx_L1;}
  if (__Pyx_SetVtable(__pyx_type_13pmat_jacobian_PinholeCameraModelWithJacobian.tp_dict, __pyx_vtabptr_13pmat_jacobian_PinholeCameraModelWithJacobian) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 29; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "PinholeCameraModelWithJacobian", (PyObject *)&__pyx_type_13pmat_jacobian_PinholeCameraModelWithJacobian) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 29; goto __pyx_L1;}
  __pyx_ptype_13pmat_jacobian_PinholeCameraModelWithJacobian = &__pyx_type_13pmat_jacobian_PinholeCameraModelWithJacobian;

  /* "/home/astraw/src/kookaburra/flydra/src/pmat_jacobian.pyx":2 */
  __pyx_1 = __Pyx_Import(__pyx_n_numpy, 0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_numpy, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/home/astraw/src/kookaburra/flydra/src/pmat_jacobian.pyx":101 */
  return;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("pmat_jacobian");
}

static char *__pyx_filenames[] = {
  "pmat_jacobian.pyx",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static int __Pyx_GetStarArgs(
    PyObject **args, 
    PyObject **kwds,
    char *kwd_list[], 
    Py_ssize_t nargs,
    PyObject **args2, 
    PyObject **kwds2,
    char rqd_kwds[])
{
    PyObject *x = 0, *args1 = 0, *kwds1 = 0;
    int i;
    char **p;
    
    if (args2)
        *args2 = 0;
    if (kwds2)
        *kwds2 = 0;
    
    if (args2) {
        args1 = PyTuple_GetSlice(*args, 0, nargs);
        if (!args1)
            goto bad;
        *args2 = PyTuple_GetSlice(*args, nargs, PyTuple_GET_SIZE(*args));
        if (!*args2)
            goto bad;
    }
    else if (PyTuple_GET_SIZE(*args) > nargs) {
        int m = nargs;
        int n = PyTuple_GET_SIZE(*args);
        PyErr_Format(PyExc_TypeError,
            "function takes at most %d positional arguments (%d given)",
                m, n);
        goto bad;
    }
    else {
        args1 = *args;
        Py_INCREF(args1);
    }
    
    if (rqd_kwds && !*kwds)
            for (i = 0, p = kwd_list; *p; i++, p++)
                if (rqd_kwds[i])
                    goto missing_kwarg;
    
    if (kwds2) {
        if (*kwds) {
            kwds1 = PyDict_New();
            if (!kwds1)
                goto bad;
            *kwds2 = PyDict_Copy(*kwds);
            if (!*kwds2)
                goto bad;
            for (i = 0, p = kwd_list; *p; i++, p++) {
                x = PyDict_GetItemString(*kwds, *p);
                if (x) {
                    if (PyDict_SetItemString(kwds1, *p, x) < 0)
                        goto bad;
                    if (PyDict_DelItemString(*kwds2, *p) < 0)
                        goto bad;
                }
                else if (rqd_kwds && rqd_kwds[i])
                    goto missing_kwarg;
            }
        }
        else {
            *kwds2 = PyDict_New();
            if (!*kwds2)
                goto bad;
        }
    }
    else {
        kwds1 = *kwds;
        Py_XINCREF(kwds1);
        if (rqd_kwds && *kwds)
            for (i = 0, p = kwd_list; *p; i++, p++)
                if (rqd_kwds[i] && !PyDict_GetItemString(*kwds, *p))
                        goto missing_kwarg;
    }
    
    *args = args1;
    *kwds = kwds1;
    return 0;
missing_kwarg:
    PyErr_Format(PyExc_TypeError,
        "required keyword argument '%s' is missing", *p);
bad:
    Py_XDECREF(args1);
    Py_XDECREF(kwds1);
    if (args2) {
        Py_XDECREF(*args2);
    }
    if (kwds2) {
        Py_XDECREF(*kwds2);
    }
    return -1;
}

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list) {
    PyObject *__import__ = 0;
    PyObject *empty_list = 0;
    PyObject *module = 0;
    PyObject *global_dict = 0;
    PyObject *empty_dict = 0;
    PyObject *list;
    __import__ = PyObject_GetAttrString(__pyx_b, "__import__");
    if (!__import__)
        goto bad;
    if (from_list)
        list = from_list;
    else {
        empty_list = PyList_New(0);
        if (!empty_list)
            goto bad;
        list = empty_list;
    }
    global_dict = PyModule_GetDict(__pyx_m);
    if (!global_dict)
        goto bad;
    empty_dict = PyDict_New();
    if (!empty_dict)
        goto bad;
    module = PyObject_CallFunction(__import__, "OOOO",
        name, global_dict, empty_dict, list);
bad:
    Py_XDECREF(empty_list);
    Py_XDECREF(__import__);
    Py_XDECREF(empty_dict);
    return module;
}

static void __Pyx_UnpackError(void) {
    PyErr_SetString(PyExc_ValueError, "unpack sequence of wrong size");
}

static PyObject *__Pyx_UnpackItem(PyObject *iter) {
    PyObject *item;
    if (!(item = PyIter_Next(iter))) {
        if (!PyErr_Occurred())
            __Pyx_UnpackError();
    }
    return item;
}

static int __Pyx_EndUnpack(PyObject *iter) {
    PyObject *item;
    if ((item = PyIter_Next(iter))) {
        Py_DECREF(item);
        __Pyx_UnpackError();
        return -1;
    }
    else if (!PyErr_Occurred())
        return 0;
    else
        return -1;
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t) {
    while (t->p) {
        *t->p = PyString_InternFromString(t->s);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

static int __Pyx_SetVtable(PyObject *dict, void *vtable) {
    PyObject *pycobj = 0;
    int result;
    
    pycobj = PyCObject_FromVoidPtr(vtable, 0);
    if (!pycobj)
        goto bad;
    if (PyDict_SetItemString(dict, "__pyx_vtable__", pycobj) < 0)
        goto bad;
    result = 0;
    goto done;

bad:
    result = -1;
done:
    Py_XDECREF(pycobj);
    return result;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_tuple = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    py_funcname = PyString_FromString(funcname);
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_tuple = PyTuple_New(0);
    if (!empty_tuple) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        empty_tuple,  /*PyObject *consts,*/
        empty_tuple,  /*PyObject *names,*/
        empty_tuple,  /*PyObject *varnames,*/
        empty_tuple,  /*PyObject *freevars,*/
        empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_tuple);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}
