name: build-and-test

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]
  schedule:
    # At 23:25 on Thursday.
    - cron: "25 23 * * 4"

jobs:

  # Build on all platforms
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-latest, macos-11, macos-latest, windows-2019, windows-latest]
        python-version: [ '3.8', '3.9' ]

    steps:
    - uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - name: Upgrade pip
      run: python -m pip install --upgrade pip
    - name: Install requirements for flydra_core
      run: python -m pip install -r ./flydra_core/requirements.txt
    - name: Build and install flydra_core
      run: python -m pip install ./flydra_core
    - name: Install requirements for flydra_analysis
      run: python -m pip install -r ./flydra_analysis/requirements.txt
    - name: Build and install flydra_analysis
      run: python -m pip install ./flydra_analysis

  # Test on Ubuntu with system python
  test-ubuntu-system-python:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Update package index
      run: sudo apt-get update
    - name: Install system packages
      run: sudo apt-get install -y libcairo2-dev # mayavi2 python3-sympy python3-docopt python3-cherrypy3 python3-pkgconfig python-is-python3 octave
    - name: Build and install flydra_core
      run: |
        cd flydra_core
        python setup.py install --user
    - name: Install missing dependencies for flydra_core
      run: python -m pip install -r ./flydra_core/requirements.txt
    - name: Test flydra_core
      run: |
        # Run these tests in a different directory to ensure we are testing an installed version.
        cd docs
        python -c "import nose; print(nose.__version__)"
        python -c "import nose; nose.run_exit()" --eval-attr="not (known_fail or slow_command)" --config ../flydra_core/setup.cfg
    - name: Install missing dependencies for flydra_analysis
      run: python -m pip install -r ./flydra_analysis/requirements.txt
    - name: Build and install flydra_analysis
      run: |
        cd flydra_analysis
        python setup.py install --user
    - name: Test flydra_analysis
      run: |
        cd flydra_analysis
        ./run_tests.sh -vv
