name: build-and-test

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]
  schedule:
    # At 23:25 on Thursday.
    - cron: "25 23 * * 4"

jobs:

  # Build on all platforms
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-10.15, macos-11.0, windows-2019]
        python-version: [ '3.8', '3.9' ]

    steps:
    - uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - name: Upgrade pip
      run: python -m pip install --upgrade pip
    - name: Install requirements for flydra_core
      run: python -m pip install -r ./flydra_core/requirements.txt
    - name: Build and install flydra_core
      run: python -m pip install ./flydra_core
    - name: Install requirements for flydra_analysis
      run: python -m pip install -r ./flydra_analysis/requirements.txt
    - name: Build and install flydra_analysis
      run: python -m pip install ./flydra_analysis

  # Test on Ubuntu with system python
  test-ubuntu-system-python:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
    - uses: actions/checkout@v2
    - name: Update Ubuntu system package index
      run: sudo apt-get update
    - name: Install system packages (Ubuntu 20.04)
      run: sudo apt-get install -y cython3 python3-cairo python3-numpy python3-scipy python3-nose python3-h5py python3-pandas mayavi2 python3-sympy python3-docopt python3-cherrypy3 python3-matplotlib python3-progressbar python3-tables python3-six python3-pkgconfig python-is-python3 octave python3-pil python3-tzlocal python3-aggdraw
    - name: Build and install flydra_core
      run: |
        cd flydra_core
        python setup.py install --user
    - name: Install missing dependencies for flydra_core
      run: python -m pip install -r ./flydra_core/requirements.txt
    - name: Test flydra_core
      run: |
        # Run these tests in a different directory to ensure we are testing an installed version.
        cd docs
        python -c "import nose; print(nose.__version__)"
        python -c "import nose; nose.run_exit()" --eval-attr="not (known_fail or slow_command)" --config ../flydra_core/setup.cfg
    - name: Install missing dependencies for flydra_analysis
      run: python -m pip install -r ./flydra_analysis/requirements.txt
    - name: Build and install flydra_analysis
      run: |
        cd flydra_analysis
        python setup.py install --user
    - name: Test flydra_analysis
      run: |
        cd flydra_analysis
        ./run_tests.sh -vv
