/* Generated by Pyrex 0.9.3 on Mon Nov 29 18:32:05 2004 */

#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#include "numarray/numarray.h"
#include "numarray/libnumarray.h"
#include "stdlib.h"
#include "ippdefs.h"
#include "ippcore.h"
#include "ippi.h"
#include "ippcv.h"
#include "ipps.h"


typedef struct {PyObject **p; char *s;} __Pyx_InternTabEntry; /*proto*/
typedef struct {PyObject **p; char *s; long n;} __Pyx_StringTabEntry; /*proto*/
static PyObject *__Pyx_UnpackItem(PyObject *, int); /*proto*/
static int __Pyx_EndUnpack(PyObject *, int); /*proto*/
static int __Pyx_PrintItem(PyObject *); /*proto*/
static int __Pyx_PrintNewline(void); /*proto*/
static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb); /*proto*/
static void __Pyx_ReRaise(void); /*proto*/
static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list); /*proto*/
static PyObject *__Pyx_GetExcValue(void); /*proto*/
static int __Pyx_ArgTypeTest(PyObject *obj, PyTypeObject *type, int none_allowed, char *name); /*proto*/
static int __Pyx_TypeTest(PyObject *obj, PyTypeObject *type); /*proto*/
static int __Pyx_GetStarArgs(PyObject **args, PyObject **kwds, char *kwd_list[], int nargs, PyObject **args2, PyObject **kwds2); /*proto*/
static void __Pyx_WriteUnraisable(char *name); /*proto*/
static void __Pyx_AddTraceback(char *funcname); /*proto*/
static PyTypeObject *__Pyx_ImportType(char *module_name, char *class_name, long size);  /*proto*/
static int __Pyx_SetVtable(PyObject *dict, void *vtable); /*proto*/
static int __Pyx_GetVtable(PyObject *dict, void *vtabptr); /*proto*/
static PyObject *__Pyx_CreateClass(PyObject *bases, PyObject *dict, PyObject *name, char *modname); /*proto*/
static int __Pyx_InternStrings(__Pyx_InternTabEntry *t); /*proto*/
static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/
static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
staticforward char **__pyx_f;

/* Declarations from c_numarray */

enum  {
  __pyx_e_10c_numarray_CHARTYPE = 97,
};

static PyTypeObject *__pyx_ptype_10c_numarray__numarray = 0;

/* Declarations from c_lib */


/* Declarations from ipp */


/* Declarations from moments */

staticforward PyTypeObject __pyx_type_7moments_MomentState;

typedef struct {
  PyObject_HEAD
  struct __pyx_vtabstruct_7moments_MomentState *__pyx_vtab;
  IppiMomentState_64f (*pState);
} __pyx_obj_7moments_MomentState;

struct __pyx_vtabstruct_7moments_MomentState {
  void ((*fill_moments_8u_C1R)(__pyx_obj_7moments_MomentState *,Ipp8u (*),int ,IppiSize ));
};
static struct __pyx_vtabstruct_7moments_MomentState *__pyx_vtabptr_7moments_MomentState;

static PyTypeObject *__pyx_ptype_7moments_MomentState = 0;
static PyObject *__pyx_k3;
static void (__pyx_f_7moments_CHK(IppStatus )); /*proto*/

/* Implementation of moments */


static PyObject *__pyx_n_nx;
static PyObject *__pyx_n_c_numarray;
static PyObject *__pyx_n_c_lib;
static PyObject *__pyx_n_ipp;
static PyObject *__pyx_n_IPPError;
static PyObject *__pyx_n_numarray;
static PyObject *__pyx_n_Exception;
static PyObject *__pyx_n_False;

static void __pyx_f_7moments_CHK(IppStatus __pyx_v_errval) {
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;

  /* "/home/astraw/kookaburra/flydra/misc_ipp/moments.pyx":17 */
  __pyx_1 = (__pyx_v_errval != 0);
  if (__pyx_1) {

    /* "/home/astraw/kookaburra/flydra/misc_ipp/moments.pyx":18 */
    __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_IPPError); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 18; goto __pyx_L1;}
    __pyx_3 = PyString_FromString(ippCoreGetStatusString(__pyx_v_errval)); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 18; goto __pyx_L1;}
    __pyx_4 = PyTuple_New(1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 18; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_4, 0, __pyx_3);
    __pyx_3 = 0;
    __pyx_3 = PyObject_CallObject(__pyx_2, __pyx_4); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 18; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __Pyx_Raise(__pyx_3, 0, 0);
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 18; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("moments.CHK");
  __pyx_L0:;
}

static int __pyx_f_7moments_11MomentState___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_f_7moments_11MomentState___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  int __pyx_r;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return -1;
  Py_INCREF(__pyx_v_self);

  /* "/home/astraw/kookaburra/flydra/misc_ipp/moments.pyx":23 */
  __pyx_f_7moments_CHK(ippiMomentInitAlloc_64f((&((__pyx_obj_7moments_MomentState *)__pyx_v_self)->pState),ippAlgHintFast)); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 23; goto __pyx_L1;}

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("moments.MomentState.__init__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_7moments_11MomentState___del__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_7moments_11MomentState___del__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/home/astraw/kookaburra/flydra/misc_ipp/moments.pyx":25 */
  __pyx_f_7moments_CHK(ippiMomentFree_64f(((__pyx_obj_7moments_MomentState *)__pyx_v_self)->pState)); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 25; goto __pyx_L1;}

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("moments.MomentState.__del__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_n_len;
static PyObject *__pyx_n_shape;
static PyObject *__pyx_n_type;
static PyObject *__pyx_n_UInt8;
static PyObject *__pyx_n_MemoryError;

static PyObject *__pyx_k4p;

static char (__pyx_k4[]) = "Error allocating memory by IPP";

static PyObject *__pyx_f_7moments_11MomentState_fill_moment(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_7moments_11MomentState_fill_moment(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyArrayObject *__pyx_v_image = 0;
  Ipp8u (*__pyx_v_pSrc);
  int __pyx_v_srcStep;
  IppiSize __pyx_v_roiSize;
  int __pyx_v_i;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  int __pyx_4;
  int __pyx_5;
  static char *__pyx_argnames[] = {"image",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_image)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_image);
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_image), __pyx_ptype_10c_numarray__numarray, 1, "image")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 26; goto __pyx_L1;}

  /* "/home/astraw/kookaburra/flydra/misc_ipp/moments.pyx":32 */
  __pyx_1 = __Pyx_GetName(__pyx_b, __pyx_n_len); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; goto __pyx_L1;}
  __pyx_2 = PyObject_GetAttr(((PyObject *)__pyx_v_image), __pyx_n_shape); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; goto __pyx_L1;}
  __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_2);
  __pyx_2 = 0;
  __pyx_2 = PyObject_CallObject(__pyx_1, __pyx_3); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_1 = PyInt_FromLong(2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; goto __pyx_L1;}
  if (PyObject_Cmp(__pyx_2, __pyx_1, &__pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; goto __pyx_L1;}
  __pyx_4 = __pyx_4 == 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  if (!__pyx_4) {
    PyErr_SetNone(PyExc_AssertionError);
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; goto __pyx_L1;}
  }

  /* "/home/astraw/kookaburra/flydra/misc_ipp/moments.pyx":33 */
  __pyx_3 = PyObject_GetAttr(((PyObject *)__pyx_v_image), __pyx_n_type); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 33; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 33; goto __pyx_L1;}
  __pyx_1 = PyObject_CallObject(__pyx_3, __pyx_2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 33; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_3 = __Pyx_GetName(__pyx_m, __pyx_n_nx); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 33; goto __pyx_L1;}
  __pyx_2 = PyObject_GetAttr(__pyx_3, __pyx_n_UInt8); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 33; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  if (PyObject_Cmp(__pyx_1, __pyx_2, &__pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 33; goto __pyx_L1;}
  __pyx_4 = __pyx_4 == 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (!__pyx_4) {
    PyErr_SetNone(PyExc_AssertionError);
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 33; goto __pyx_L1;}
  }

  /* "/home/astraw/kookaburra/flydra/misc_ipp/moments.pyx":35 */
  __pyx_3 = PyObject_GetAttr(((PyObject *)__pyx_v_image), __pyx_n_shape); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 35; goto __pyx_L1;}
  __pyx_1 = __Pyx_UnpackItem(__pyx_3, 0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 35; goto __pyx_L1;}
  __pyx_4 = PyInt_AsLong(__pyx_1); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 35; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_v_roiSize.height = __pyx_4;
  __pyx_2 = __Pyx_UnpackItem(__pyx_3, 1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 35; goto __pyx_L1;}
  __pyx_5 = PyInt_AsLong(__pyx_2); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 35; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_v_roiSize.width = __pyx_5;
  if (__Pyx_EndUnpack(__pyx_3, 2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 35; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "/home/astraw/kookaburra/flydra/misc_ipp/moments.pyx":38 */
  __pyx_v_pSrc = ippiMalloc_8u_C1(__pyx_v_roiSize.width,__pyx_v_roiSize.height,(&__pyx_v_srcStep));

  /* "/home/astraw/kookaburra/flydra/misc_ipp/moments.pyx":39 */
  __pyx_4 = (__pyx_v_pSrc == 0);
  if (__pyx_4) {
    __pyx_1 = __Pyx_GetName(__pyx_b, __pyx_n_MemoryError); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 39; goto __pyx_L1;}
    __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 39; goto __pyx_L1;}
    Py_INCREF(__pyx_k4p);
    PyTuple_SET_ITEM(__pyx_2, 0, __pyx_k4p);
    __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 39; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __Pyx_Raise(__pyx_3, 0, 0);
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 39; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/home/astraw/kookaburra/flydra/misc_ipp/moments.pyx":42 */
  __pyx_5 = __pyx_v_roiSize.height;
  for (__pyx_v_i = 0; __pyx_v_i < __pyx_5; ++__pyx_v_i) {

    /* "/home/astraw/kookaburra/flydra/misc_ipp/moments.pyx":43 */
    memcpy((__pyx_v_pSrc + (__pyx_v_srcStep * __pyx_v_i)),(__pyx_v_image->data + (__pyx_v_roiSize.width * __pyx_v_i)),__pyx_v_roiSize.width);
    __pyx_L3:;
  }
  __pyx_L4:;

  /* "/home/astraw/kookaburra/flydra/misc_ipp/moments.pyx":48 */
  ((struct __pyx_vtabstruct_7moments_MomentState *)((__pyx_obj_7moments_MomentState *)__pyx_v_self)->__pyx_vtab)->fill_moments_8u_C1R(((__pyx_obj_7moments_MomentState *)__pyx_v_self),__pyx_v_pSrc,__pyx_v_srcStep,__pyx_v_roiSize);

  /* "/home/astraw/kookaburra/flydra/misc_ipp/moments.pyx":51 */
  ippiFree(__pyx_v_pSrc);

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("moments.MomentState.fill_moment");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_image);
  return __pyx_r;
}

static void __pyx_f_7moments_11MomentState_fill_moments_8u_C1R(__pyx_obj_7moments_MomentState *__pyx_v_self,Ipp8u (*__pyx_v_pSrc),int __pyx_v_srcStep,IppiSize __pyx_v_roiSize) {
  Py_INCREF(__pyx_v_self);

  /* "/home/astraw/kookaburra/flydra/misc_ipp/moments.pyx":54 */
  __pyx_f_7moments_CHK(ippiMoments64f_8u_C1R(__pyx_v_pSrc,__pyx_v_srcStep,__pyx_v_roiSize,__pyx_v_self->pState)); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; goto __pyx_L1;}

  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_WriteUnraisable("moments.MomentState.fill_moments_8u_C1R");
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
}

static PyObject *__pyx_n_central;
static PyObject *__pyx_n_spatial;
static PyObject *__pyx_n_ValueError;

static PyObject *__pyx_k7p;

static char (__pyx_k7[]) = "don't understand moment type '%s'";

static PyObject *__pyx_f_7moments_11MomentState_get_moment(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_7moments_11MomentState_get_moment(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_typ = 0;
  int __pyx_v_order_M;
  int __pyx_v_order_N;
  int __pyx_v_channel;
  PyObject *__pyx_v_normalized = 0;
  double __pyx_v_result;
  IppiPoint __pyx_v_roi_offset;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  static char *__pyx_argnames[] = {"typ","order_M","order_N","channel","normalized",0};
  __pyx_v_normalized = __pyx_k3;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "Oiii|O", __pyx_argnames, &__pyx_v_typ, &__pyx_v_order_M, &__pyx_v_order_N, &__pyx_v_channel, &__pyx_v_normalized)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_typ);
  Py_INCREF(__pyx_v_normalized);

  /* "/home/astraw/kookaburra/flydra/misc_ipp/moments.pyx":58 */
  if (PyObject_Cmp(__pyx_v_typ, __pyx_n_central, &__pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; goto __pyx_L1;}
  __pyx_1 = __pyx_1 == 0;
  if (__pyx_1) {

    /* "/home/astraw/kookaburra/flydra/misc_ipp/moments.pyx":59 */
    __pyx_1 = PyObject_IsTrue(__pyx_v_normalized); if (__pyx_1 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 59; goto __pyx_L1;}
    if (__pyx_1) {

      /* "/home/astraw/kookaburra/flydra/misc_ipp/moments.pyx":60 */
      __pyx_f_7moments_CHK(ippiGetNormalizedCentralMoment_64f(((__pyx_obj_7moments_MomentState *)__pyx_v_self)->pState,__pyx_v_order_M,__pyx_v_order_N,__pyx_v_channel,(&__pyx_v_result))); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 60; goto __pyx_L1;}
      goto __pyx_L3;
    }
    /*else*/ {

      /* "/home/astraw/kookaburra/flydra/misc_ipp/moments.pyx":66 */
      __pyx_f_7moments_CHK(ippiGetCentralMoment_64f(((__pyx_obj_7moments_MomentState *)__pyx_v_self)->pState,__pyx_v_order_M,__pyx_v_order_N,__pyx_v_channel,(&__pyx_v_result))); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 66; goto __pyx_L1;}
    }
    __pyx_L3:;
    goto __pyx_L2;
  }
  if (PyObject_Cmp(__pyx_v_typ, __pyx_n_spatial, &__pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 71; goto __pyx_L1;}
  __pyx_1 = __pyx_1 == 0;
  if (__pyx_1) {

    /* "/home/astraw/kookaburra/flydra/misc_ipp/moments.pyx":72 */
    __pyx_v_roi_offset.x = 0;

    /* "/home/astraw/kookaburra/flydra/misc_ipp/moments.pyx":73 */
    __pyx_v_roi_offset.y = 0;

    /* "/home/astraw/kookaburra/flydra/misc_ipp/moments.pyx":74 */
    __pyx_1 = PyObject_IsTrue(__pyx_v_normalized); if (__pyx_1 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 74; goto __pyx_L1;}
    if (__pyx_1) {

      /* "/home/astraw/kookaburra/flydra/misc_ipp/moments.pyx":75 */
      __pyx_f_7moments_CHK(ippiGetNormalizedSpatialMoment_64f(((__pyx_obj_7moments_MomentState *)__pyx_v_self)->pState,__pyx_v_order_M,__pyx_v_order_N,__pyx_v_channel,__pyx_v_roi_offset,(&__pyx_v_result))); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 75; goto __pyx_L1;}
      goto __pyx_L4;
    }
    /*else*/ {

      /* "/home/astraw/kookaburra/flydra/misc_ipp/moments.pyx":82 */
      __pyx_f_7moments_CHK(ippiGetSpatialMoment_64f(((__pyx_obj_7moments_MomentState *)__pyx_v_self)->pState,__pyx_v_order_M,__pyx_v_order_N,__pyx_v_channel,__pyx_v_roi_offset,(&__pyx_v_result))); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 82; goto __pyx_L1;}
    }
    __pyx_L4:;
    goto __pyx_L2;
  }
  /*else*/ {

    /* "/home/astraw/kookaburra/flydra/misc_ipp/moments.pyx":89 */
    __pyx_2 = __Pyx_GetName(__pyx_b, __pyx_n_ValueError); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 89; goto __pyx_L1;}
    __pyx_3 = PyNumber_Remainder(__pyx_k7p, __pyx_v_typ); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 89; goto __pyx_L1;}
    __pyx_4 = PyTuple_New(1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 89; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_4, 0, __pyx_3);
    __pyx_3 = 0;
    __pyx_3 = PyObject_CallObject(__pyx_2, __pyx_4); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 89; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __Pyx_Raise(__pyx_3, 0, 0);
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 89; goto __pyx_L1;}
  }
  __pyx_L2:;

  /* "/home/astraw/kookaburra/flydra/misc_ipp/moments.pyx":90 */
  __pyx_2 = PyFloat_FromDouble(__pyx_v_result); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 90; goto __pyx_L1;}
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("moments.MomentState.get_moment");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_typ);
  Py_DECREF(__pyx_v_normalized);
  return __pyx_r;
}

static __Pyx_InternTabEntry __pyx_intern_tab[] = {
  {&__pyx_n_Exception, "Exception"},
  {&__pyx_n_False, "False"},
  {&__pyx_n_IPPError, "IPPError"},
  {&__pyx_n_MemoryError, "MemoryError"},
  {&__pyx_n_UInt8, "UInt8"},
  {&__pyx_n_ValueError, "ValueError"},
  {&__pyx_n_c_lib, "c_lib"},
  {&__pyx_n_c_numarray, "c_numarray"},
  {&__pyx_n_central, "central"},
  {&__pyx_n_ipp, "ipp"},
  {&__pyx_n_len, "len"},
  {&__pyx_n_numarray, "numarray"},
  {&__pyx_n_nx, "nx"},
  {&__pyx_n_shape, "shape"},
  {&__pyx_n_spatial, "spatial"},
  {&__pyx_n_type, "type"},
  {0, 0}
};

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_k4p, __pyx_k4, sizeof(__pyx_k4)},
  {&__pyx_k7p, __pyx_k7, sizeof(__pyx_k7)},
  {0, 0, 0}
};
static struct __pyx_vtabstruct_7moments_MomentState __pyx_vtable_7moments_MomentState;

static PyObject *__pyx_tp_new_7moments_MomentState(PyTypeObject *t, PyObject *a, PyObject *k) {
  PyObject *o = (*t->tp_alloc)(t, 0);
  __pyx_obj_7moments_MomentState *p = (__pyx_obj_7moments_MomentState *)o;
  (struct __pyx_vtabstruct_7moments_MomentState *)p->__pyx_vtab = __pyx_vtabptr_7moments_MomentState;
  return o;
}

static void __pyx_tp_dealloc_7moments_MomentState(PyObject *o) {
  __pyx_obj_7moments_MomentState *p = (__pyx_obj_7moments_MomentState *)o;
  (*o->ob_type->tp_free)(o);
}

static int __pyx_tp_traverse_7moments_MomentState(PyObject *o, visitproc v, void *a) {
  int e;
  __pyx_obj_7moments_MomentState *p = (__pyx_obj_7moments_MomentState *)o;
  return 0;
}

static int __pyx_tp_clear_7moments_MomentState(PyObject *o) {
  __pyx_obj_7moments_MomentState *p = (__pyx_obj_7moments_MomentState *)o;
  return 0;
}

static struct PyMethodDef __pyx_methods_7moments_MomentState[] = {
  {"__del__", (PyCFunction)__pyx_f_7moments_11MomentState___del__, METH_VARARGS|METH_KEYWORDS, 0},
  {"fill_moment", (PyCFunction)__pyx_f_7moments_11MomentState_fill_moment, METH_VARARGS|METH_KEYWORDS, 0},
  {"get_moment", (PyCFunction)__pyx_f_7moments_11MomentState_get_moment, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_MomentState = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
};

static PySequenceMethods __pyx_tp_as_sequence_MomentState = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_MomentState = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_MomentState = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

statichere PyTypeObject __pyx_type_7moments_MomentState = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "moments.MomentState", /*tp_name*/
  sizeof(__pyx_obj_7moments_MomentState), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_7moments_MomentState, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_MomentState, /*tp_as_number*/
  &__pyx_tp_as_sequence_MomentState, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_MomentState, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_MomentState, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE, /*tp_flags*/
  0, /*tp_doc*/
  __pyx_tp_traverse_7moments_MomentState, /*tp_traverse*/
  __pyx_tp_clear_7moments_MomentState, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_7moments_MomentState, /*tp_methods*/
  0, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  __pyx_f_7moments_11MomentState___init__, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_7moments_MomentState, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static struct PyMethodDef __pyx_methods[] = {
  {0, 0, 0, 0}
};

DL_EXPORT(void) initmoments(void); /*proto*/
DL_EXPORT(void) initmoments(void) {
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  __pyx_m = Py_InitModule4("moments", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 4; goto __pyx_L1;};
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 4; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 4; goto __pyx_L1;};
  if (__Pyx_InternStrings(__pyx_intern_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 4; goto __pyx_L1;};
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 4; goto __pyx_L1;};
  __pyx_ptype_10c_numarray__numarray = __Pyx_ImportType("numarray._numarray", "_numarray", sizeof(PyArrayObject)); if (!__pyx_ptype_10c_numarray__numarray) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 56; goto __pyx_L1;}
  __pyx_vtabptr_7moments_MomentState = &__pyx_vtable_7moments_MomentState;
  __pyx_vtable_7moments_MomentState.fill_moments_8u_C1R = (void *)__pyx_f_7moments_11MomentState_fill_moments_8u_C1R;
  if (PyType_Ready(&__pyx_type_7moments_MomentState) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 20; goto __pyx_L1;}
  if (__Pyx_SetVtable(__pyx_type_7moments_MomentState.tp_dict, __pyx_vtabptr_7moments_MomentState) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 20; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "MomentState", (PyObject *)&__pyx_type_7moments_MomentState) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 20; goto __pyx_L1;}
  __pyx_ptype_7moments_MomentState = &__pyx_type_7moments_MomentState;

  /* "/home/astraw/kookaburra/flydra/misc_ipp/moments.pyx":4 */
  __pyx_1 = __Pyx_Import(__pyx_n_numarray, 0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 4; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_nx, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 4; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/home/astraw/kookaburra/flydra/misc_ipp/moments.pyx":7 */
  import_libnumarray();

  /* "/home/astraw/kookaburra/flydra/misc_ipp/moments.pyx":13 */
  __pyx_1 = PyDict_New(); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 13; goto __pyx_L1;}
  __pyx_2 = __Pyx_GetName(__pyx_b, __pyx_n_Exception); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 13; goto __pyx_L1;}
  __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 13; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_2);
  __pyx_2 = 0;
  __pyx_2 = __Pyx_CreateClass(__pyx_3, __pyx_1, __pyx_n_IPPError, "moments"); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 13; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "/home/astraw/kookaburra/flydra/misc_ipp/moments.pyx":14 */
  if (PyObject_SetAttr(__pyx_m, __pyx_n_IPPError, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 13; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/home/astraw/kookaburra/flydra/misc_ipp/moments.pyx":55 */
  __pyx_3 = __Pyx_GetName(__pyx_b, __pyx_n_False); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 55; goto __pyx_L1;}
  __pyx_k3 = __pyx_3;
  __pyx_3 = 0;
  return;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("moments");
}

static char *__pyx_filenames[] = {
  "moments.pyx",
  "c_numarray.pxd",
};
statichere char **__pyx_f = __pyx_filenames;

/* Runtime support code */

static int __Pyx_ArgTypeTest(PyObject *obj, PyTypeObject *type, int none_allowed, char *name) {
    if (!type) {
        PyErr_Format(PyExc_SystemError, "Missing type object");
        return 0;
    }
    if ((none_allowed && obj == Py_None) || PyObject_TypeCheck(obj, type))
        return 1;
    PyErr_Format(PyExc_TypeError,
        "Argument '%s' has incorrect type (expected %s, got %s)",
        name, type->tp_name, obj->ob_type->tp_name);
    return 0;
}

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list) {
    PyObject *__import__ = 0;
    PyObject *empty_list = 0;
    PyObject *module = 0;
    PyObject *global_dict = 0;
    PyObject *empty_dict = 0;
    PyObject *list;
    __import__ = PyObject_GetAttrString(__pyx_b, "__import__");
    if (!__import__)
        goto bad;
    if (from_list)
        list = from_list;
    else {
        empty_list = PyList_New(0);
        if (!empty_list)
            goto bad;
        list = empty_list;
    }
    global_dict = PyModule_GetDict(__pyx_m);
    if (!global_dict)
        goto bad;
    empty_dict = PyDict_New();
    if (!empty_dict)
        goto bad;
    module = PyObject_CallFunction(__import__, "OOOO",
        name, global_dict, empty_dict, list);
bad:
    Py_XDECREF(empty_list);
    Py_XDECREF(__import__);
    Py_XDECREF(empty_dict);
    return module;
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

static PyObject *__Pyx_CreateClass(
    PyObject *bases, PyObject *dict, PyObject *name, char *modname)
{
    PyObject *py_modname;
    PyObject *result = 0;
    
    py_modname = PyString_FromString(modname);
    if (!py_modname)
        goto bad;
    if (PyDict_SetItemString(dict, "__module__", py_modname) < 0)
        goto bad;
    result = PyClass_New(bases, dict, name);
bad:
    Py_XDECREF(py_modname);
    return result;
}

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb) {
    Py_XINCREF(type);
    Py_XINCREF(value);
    Py_XINCREF(tb);
    /* First, check the traceback argument, replacing None with NULL. */
    if (tb == Py_None) {
        Py_DECREF(tb);
        tb = 0;
    }
    else if (tb != NULL && !PyTraceBack_Check(tb)) {
        PyErr_SetString(PyExc_TypeError,
            "raise: arg 3 must be a traceback or None");
        goto raise_error;
    }
    /* Next, replace a missing value with None */
    if (value == NULL) {
        value = Py_None;
        Py_INCREF(value);
    }
    /* Next, repeatedly, replace a tuple exception with its first item */
    while (PyTuple_Check(type) && PyTuple_Size(type) > 0) {
        PyObject *tmp = type;
        type = PyTuple_GET_ITEM(type, 0);
        Py_INCREF(type);
        Py_DECREF(tmp);
    }
    if (PyString_Check(type))
        ;
    else if (PyClass_Check(type))
        ; /*PyErr_NormalizeException(&type, &value, &tb);*/
    else if (PyInstance_Check(type)) {
        /* Raising an instance.  The value should be a dummy. */
        if (value != Py_None) {
            PyErr_SetString(PyExc_TypeError,
              "instance exception may not have a separate value");
            goto raise_error;
        }
        else {
            /* Normalize to raise <class>, <instance> */
            Py_DECREF(value);
            value = type;
            type = (PyObject*) ((PyInstanceObject*)type)->in_class;
            Py_INCREF(type);
        }
    }
    else {
        /* Not something you can raise.  You get an exception
           anyway, just not what you specified :-) */
        PyErr_Format(PyExc_TypeError,
                 "exceptions must be strings, classes, or "
                 "instances, not %s", type->ob_type->tp_name);
        goto raise_error;
    }
    PyErr_Restore(type, value, tb);
    return;
raise_error:
    Py_XDECREF(value);
    Py_XDECREF(type);
    Py_XDECREF(tb);
    return;
}

static void __Pyx_UnpackError(void) {
    PyErr_SetString(PyExc_ValueError, "unpack sequence of wrong size");
}

static PyObject *__Pyx_UnpackItem(PyObject *seq, int i) {
  PyObject *item;
  if (!(item = PySequence_GetItem(seq, i))) {
    if (PyErr_ExceptionMatches(PyExc_IndexError))
    	__Pyx_UnpackError();
  }
  return item;
}

static int __Pyx_EndUnpack(PyObject *seq, int i) {
  PyObject *item;
  if (item = PySequence_GetItem(seq, i)) {
    Py_DECREF(item);
    __Pyx_UnpackError();
    return -1;
  }
  PyErr_Clear();
    return 0;
}

static void __Pyx_WriteUnraisable(char *name) {
    PyObject *old_exc, *old_val, *old_tb;
    PyObject *ctx;
    PyErr_Fetch(&old_exc, &old_val, &old_tb);
    ctx = PyString_FromString(name);
    PyErr_Restore(old_exc, old_val, old_tb);
    if (!ctx)
        ctx = Py_None;
    PyErr_WriteUnraisable(ctx);
}

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t) {
    while (t->p) {
        *t->p = PyString_InternFromString(t->s);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

static PyTypeObject *__Pyx_ImportType(char *module_name, char *class_name, 
    long size) 
{
    PyObject *py_module_name = 0;
    PyObject *py_class_name = 0;
    PyObject *py_name_list = 0;
    PyObject *py_module = 0;
    PyObject *result = 0;
    
    py_module_name = PyString_FromString(module_name);
    if (!py_module_name)
        goto bad;
    py_class_name = PyString_FromString(class_name);
    if (!py_class_name)
        goto bad;
    py_name_list = PyList_New(1);
    if (!py_name_list)
        goto bad;
    Py_INCREF(py_class_name);
    if (PyList_SetItem(py_name_list, 0, py_class_name) < 0)
        goto bad;
    py_module = __Pyx_Import(py_module_name, py_name_list);
    if (!py_module)
        goto bad;
    result = PyObject_GetAttr(py_module, py_class_name);
    if (!result)
        goto bad;
    if (!PyType_Check(result)) {
        PyErr_Format(PyExc_TypeError, 
            "%s.%s is not a type object",
            module_name, class_name);
        goto bad;
    }
    if (((PyTypeObject *)result)->tp_basicsize != size) {
        PyErr_Format(PyExc_ValueError, 
            "%s.%s does not appear to be the correct type object",
            module_name, class_name);
        goto bad;
    }
    goto done;
bad:
    Py_XDECREF(result);
    result = 0;
done:
    Py_XDECREF(py_module_name);
    Py_XDECREF(py_class_name);
    Py_XDECREF(py_name_list);
    return (PyTypeObject *)result;
}

static int __Pyx_SetVtable(PyObject *dict, void *vtable) {
    PyObject *pycobj = 0;
    int result;
    
    pycobj = PyCObject_FromVoidPtr(vtable, 0);
    if (!pycobj)
        goto bad;
    if (PyDict_SetItemString(dict, "__pyx_vtable__", pycobj) < 0)
        goto bad;
    result = 0;
    goto done;

bad:
    result = -1;
done:
    Py_XDECREF(pycobj);
    return result;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_tuple = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    py_funcname = PyString_FromString(funcname);
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_tuple = PyTuple_New(0);
    if (!empty_tuple) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        empty_tuple,  /*PyObject *consts,*/
        empty_tuple,  /*PyObject *names,*/
        empty_tuple,  /*PyObject *varnames,*/
        empty_tuple,  /*PyObject *freevars,*/
        empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_tuple);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}
